t3-oss/create-t3-app

package-lock.json
src/helpers/create.ts

closes #13 
Perhaps warrants more implementation of scaffolding into directories other than CWD, but this PR will fulfill the enhancement request in the issue.

Add scaffolding directory to log output

---

src/index.ts

Put all the prompts into an array with some type safety so that future prompts can be added and get some warnings.
The packages are now enables as a multi-select so adding more packages is easier and doesn't require a new prompt to be added.
Also put in some response messages such as when leaving name blank (Closing #11 in the process). See a demo [here (CleanShot link)](https://cleanshot-cloud-fra.accelerator.net/media/38032/Ze78t4RhWyHtcN6249n1JfUB211oD9zaQotGhnWQ.mp4).
**There is a limitation however. If selecting Next-Auth, but not Prisma, it will go ahead and create a project with both of them due to there only being one Next-Auth template available. I can look into perhaps making it so that every individual package is installed separately, and configs copied over accordingly, so …

implemented better type safety for adding future prompts

---

src/helpers/create.ts

screenshots were added in previous pr so not adding again.

feat: check if dir is empty

---

src/installers/prisma.ts

add postinstall script to package.json

---

README.md
package.json

I added support for windows by adding another script in package.json, this error popped up when trying to build:
I added some instructions in the readme so it's easier for new people to start contributing.

Feat: windows build support, more readme instructions

---

template/addons/trpc/api-handler.ts
template/addons/trpc/utils.ts

Added a helper to infer types from queries in tRPC. It is a really important one that always needs to be googled because the syntax is really difficult. I believe it is really helpful to have this in the template.
Example:
Definition: https://github.com/TheoBr/roundest-mon/blob/e2834b689941df2c61b5acb9816f675437c92df9/src/pages/api/trpc/%5Btrpc%5D.ts#L11
Implementation: https://github.com/TheoBr/roundest-mon/blob/827d89463e1fc6edb7bbb5eb814fde67f6c36381/src/pages/index.tsx#L88

Add inferQueryResponse helper for tRPC

---

package.json
pnpm-lock.yaml
src/index.ts
src/installers/prisma.ts
tsconfig.json

As per the title, added 'type-fest' as a dev dependency to provide types for package.json (which was previously throwing a linting error).
Removed extra comments from my previous PR

Fix a small linting issue and cleanup extraneous comments

---

package.json
pnpm-lock.yaml
src/helpers/create.ts
src/helpers/select-boilerplate.ts
src/installers/next-auth.ts
src/installers/prisma.ts
src/installers/tailwind.ts
src/installers/trpc.ts
tsconfig.json

Tied to #41. Totally optional as we discussed in discord, but feel free to play around with the setup. 
It looks like you might dev on a windows computer, would love to know if the updated `build` and `dev` commands work for you.

Adding TSUP as the bundler tool

---

README.md

If you follow current steps you will attempt to run start on a non-existing
- Fix is to run the build step before start

Fix Contributing Steps

---

CHANGELOG.md
package.json
src/consts.ts

Closes #65 
Investigated lots of options using `process.mainModule`, `require.main` etc but these options are not compatible with ESM. The solution I [found](https://bobbyhadz.com/blog/javascript-dirname-is-not-defined-in-es-module-scope), which was also proposed by @devkevbot in [#65 (comment)](https://github.com/nexxeln/create-t3-app/issues/65#issuecomment-1168430972) was to use `import.meta.url` instead.
```ts
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url); // path/to/create-t3-app/dist/index.js
const distPath = path.dirname(__filename); // path/to/create-t3-app/dist
export const PKG_ROOT = path.join(distPath, "../"); // path/to/create-t3-app
```
when PKG_ROOT is accurately pointing to the package root again, the template …

bug-fix: Resolve pkg root

---

src/helpers/initGit.ts

Hello there,
When you run this tool it may initialize the repository with "master" as the principal branch. 
Is it ok if we specify "main"? Should we ask the user for the default branch name?
docs: https://git-scm.com/docs/git-init
Cheers,

feat: add main as initial branch

---

template/page-studs/index/with-auth-trpc-tw.tsx
template/page-studs/index/with-trpc-tw.tsx
template/page-studs/index/with-tw.tsx

As it mentioned in issue 88 we have multiple h1 tags in one page. This PR fixing it
https://github.com/t3-oss/create-t3-app/issues/88

fix(markup): multiple h1 replaced to h2

---

template/base/src/pages/index.tsx
template/page-studs/index/with-auth-trpc-tw.tsx
template/page-studs/index/with-auth-trpc.tsx
template/page-studs/index/with-trpc-tw.tsx
template/page-studs/index/with-trpc.tsx
template/page-studs/index/with-tw.tsx

Small update to some UX things while poking around.
1. Remove `-` char, and lowercased `stack` on heading text... `This Stack uses:-` -> `This stack uses:` within templates.
2. Removed `cursor-pointer` on `div` element. Will still have hover effect but now only the link will show as clickable.

Text formatting and remove cursor for non link elements 

---

src/cli/index.ts

Consistent use of the word "TypeScript" with a capital "S". This also fixes the `short` value to show "JavaScript" when that choice is selected.
See https://github.com/SBoudrias/Inquirer.js#prompt

fix(cli): use correct spelling, fix short choices

---

template/base/package.json

Found an issue while adding the stable middleware. The eslint config is pointing to the wrong version.

fix: update eslint-config-next version

---

src/cli/index.ts
src/consts.ts
src/index.ts
src/utils/renderTitle.ts

Reenable the --version flag (good for issue tracking in case a user has an old ct3a in their global installs)
Only show the node18 warning if the user isn't using the --help or --version flags
Automatically change the 'defaultOptions' object is the user is using node18 (remove next-auth)

Quick fix for node18 user experience

---

package.json
pnpm-lock.yaml

So I've added [standard-version](https://github.com/conventional-changelog/standard-version) which is well known for generating changelog from commits and bumping your package.json to the correct version depending on the commits you've added.
`pnpm release`
Changelog example:
All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.
- add CONTRIBUTING.md for newcomers ([99f8220](https://github.com/nexxeln/create-t3-app/commit/99f8220f83a6363e5aab6c0ec33260eb059c9643))
- add inferQueryResponse helper for tRPC ([748800f](https://github.com/nexxeln/create-t3-app/commit/748800f060031da58ce2b45bd65e4fd83266ce5c))
- add main as initial branch …

feat: add standard-version for generating changelog + bump package.json

---

src/cli/index.ts
src/index.ts

fixed some spellings mistakes of an inline comment and logs

fix: fixed some typos

---

src/cli/index.ts
src/helpers/createProject.ts
src/helpers/installPackages.ts
src/helpers/logNextSteps.ts
src/helpers/scaffoldProject.ts
src/index.ts
src/installers/index.ts
src/installers/next-auth.ts
src/installers/prisma.ts
src/installers/tailwind.ts
src/installers/trpc.ts
src/utils/runPkgManagerInstall.ts

Has been discussed previously (#37, #58, #128 etc.).
Enables the `--noInstall` CLI flag and adds a prompt for it. This skips the installation process and only adds the dependency to the `package.json` and copies over the boilerplate.
I ended up using `npm show <pkg> version` for this, so for tRPC it's still kinda slow (see snippet below) since there are a lot of dependencies whose versions needs to be fetched. An alternative is to keep a config-file with all the latest versions and update that from time to time. 
There are probably also some awaits we could remove to optimize and do some more stuff async to speed up the process if we care about the time it takes to scaffold. I timed 36s to scaffold a full app with install and 18s (half) without installs.
Will document and clarify with …

feat: add noInstall flag and prompt

---

src/cli/index.ts

---
In a previous pr (#107) the short answer was changed to JavaScript. Both options should have a short options of TypeScript. The short value is shown after the question has been answered and we move on to the next question. 
If we are telling the user that we are going to use TS instead, but show them JS was the selected answer, it can cause confusion. Let's keep messaging consistent, enhance UX, and show them that TS is the only way forward, no matter their selection.

fix: language prompt short answer should both be ts

---

package.json
pnpm-lock.yaml
tsconfig.json

---
- update tsconfig to turn off emit decorator metadata flag as we aren't using any
- remove @swc/core from dev dependencies as it was only added to silence tsup emitDecorator warnings
---

chore: remove extra packages no longer needed

---

template/page-studs/index/with-tw.tsx

---
The with-tw example, and perhaps other tw examples, contain multiple unused/unneeded styles and were not optimized for users who prefer reduced or no motion. Classes were also rearranged to maintain consistency across each div. 
An examples of both unused/unneeded styling and class order:
`grid grid-cols-1 grid-rows-3 lg:grid-rows-1 md:grid-rows-1 lg:grid-cols-3 md:grid-cols-3 gap-3 mt-3 pt-3 w-full lg:w-2/3 md:w-full` 
is now 
`grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3`
When we look at `lg:grid-cols-3 md:grid-cols-3` we're saying that if `@media (min-width: 1024px)` or greater, we should have at least 3 columns in our grid. The added `lg:grid-cols-3` is redundant. The original also has this class flow from lg, md, lg, md. For clarity and readability, those specific …

fix: with-tw removed unused styles and added motion saftey

---

template/page-studs/index/with-auth-trpc-tw.tsx
template/page-studs/index/with-trpc-tw.tsx
template/page-studs/index/with-tw.tsx

---
- Added semantic elements for main content and sections
- Centered main container so it doesn't take full width on widescreens
- Implemented fixes from #148 into the other tw index versions, I saw that PR just I was about to submit this and decided to get it done
---

fix: add semantic elements and update tw classes on tw pages

---

README.md

docs: fix link to init.tips/others in README

---

template/base/package.json

---
Bump next.js version to [12.2.1](https://github.com/vercel/next.js/releases/tag/v12.2.1)
---
💯

chore: bump nextjs version to 12.2.1

---

template/addons/next-auth/restricted.ts

---
Found a minor typo and formatting error in the message returned from the `restricted.ts` endpoint when unauthorized.
---
💯

fix: Typo in restricted endpoint error

---

src/utils/renderTitle.ts

---
When installing the CLI using Yarn, the welcome is not correctly printed (as you can see in the screenshot below).
---
💯

fix: properly display the welcome title when installing with Yarn

---

src/helpers/installPackages.ts

---
Converted the interface to a type keeping the opaque types previously used,
this allows for the types to be inferred correctly passed into the `installer()` and
reveals that the `packages`  argument was potentially `undefined` and never handled.
---
💯

refactor: interface converted to type

---

src/helpers/installPackages.ts

Removed the type guard checking for packages to be undefined, which should never be the case in this function.

chore: remove unnecessary type guard

---

.yarnrc.yml
src/cli/index.ts

---
This commit adds a warning when the CLI is run using Yarn 3. This is to alert the users of possible crashes as seen in https://github.com/t3-oss/create-t3-app/issues/57.
I followed the format of https://github.com/t3-oss/create-t3-app/pull/68 as it is a similar issue.
The `.yarnrc.yml` file is necessary so that the CLI doesn't crash before we can even check whether the user is on yarn 3. See https://github.com/chalk/chalk/issues/531.
---
(screenshot has a typo in it. i fixed it, but didn't want to create another screenshot as I had already uninstalled yarn 3. Hope that's ok)

feat: add check for yarn 3

---

template/page-studs/_app/with-auth-trpc.tsx

---
Reference: https://github.com/vercel/next.js/issues/5354#issuecomment-520305040
---

fix: remove process.browser check because its deprecated

---

template/page-studs/index/with-auth-trpc.tsx

fix(template): converting to use tech props and remove tw from template

---

template/page-studs/index/with-auth-trpc-tw.tsx
template/page-studs/index/with-trpc-tw.tsx
template/page-studs/index/with-tw.tsx

---
#178 removed the style fixes done in #148 and #151, and gave all tw pages the same cards. 
This PR reapplies the style fixes and restores the original cards.
---

fix: reapply style fixes on tw pages 

---

src/installers/index.ts

---
When you dont install either prisma or next-auth, there is no need to have environment variables, so we don't need to install the boilerplate for the type-safe env-vars in this case.
---

fix: conditionally run envVars installer

---

template/base/_gitignore

---
_[Short summary/description of story/feature/bugfix]_
As mentioned in https://github.com/t3-oss/create-t3-app/issues/200, the `db.sqlite` file created by the default prisma config was not included in .gitignore. 
I believe it's better to include it - Because we're not automatically creating a 'project initialized commit', it's easy to overlook the db file among all the other files that exist in version history after you initialize the app, and accidentally commit it.
If desired this could be changed to only include that line in the .gitignore if prisma is selected during initialization, but this way is much simpler and personally I think don't think it's an issue to just include it in .gitignore for everyone.
---
💯

feat: add db.sqlite to gitignore

---

src/helpers/createProject.ts
src/helpers/installPackages.ts
src/installers/index.ts
src/installers/next-auth.ts
src/installers/prisma.ts
src/installers/tailwind.ts
src/installers/trpc.ts
src/utils/runPkgManagerInstall.ts

---
I noticed that every installer had to call `runPkgManagerInstall` with a lot of configuration, but IMHO the only configuration they should specify is the `packages` list. So, this MR adds a curryable version of `runPkgManagerInstall` that is curried by `createProject` and injected to every installer as an option. This injected function has been curried with all of the necessary configuration, allowing to clear the call in each installer.
Benefits:
- cleaner code of each installer
- adding new options to `runPkgManagerInstall` will not force adding that parameter in each installer, but instead just once in the `createProject.ts` helper where it's curried
- curried options serve only as defaults, so each installer could still override the options if needed
Another small change added …

refactor: inject curried `runPkgManagerInstall` to package installers

---

src/installers/envVars.ts
template/addons/env/env-auth.mjs
template/addons/env/env-prisma-auth.mjs
template/addons/env/env-prisma.mjs
template/addons/next-auth/api-handler-prisma.ts
template/addons/next-auth/api-handler.ts
template/addons/prisma/client.ts
template/base/next.config.mjs
template/base/src/server/env-schema.js
template/base/src/server/env-schema.mjs
template/base/src/server/env.mjs

---
This PR renames the default `next.config` file (and its dependencies) to `.mjs`, and converts syntax within those files to ESM. Because ... why not? That's the direction we're moving in anyway, and this enables importing ESM-only packages too.

feat: migrate env + next config to esm

---

src/helpers/initGit.ts
src/helpers/scaffoldProject.ts

---
This fixes #212 by immediately renaming the `_gitignore` file to `.gitignore` after copying the project files.

fix: move gitignore rename call

---

src/utils/runPkgManagerInstall.ts

---
Fix #219 by extracting the package name using regex before putting the pkg string into dependency object.

fix: handle pkg with version in noInstall mode

---

.github/workflows/PR-CI.yml
src/installers/envVars.ts
template/addons/prisma/schema.prisma
template/base/.env-example

---
Resolves https://github.com/t3-oss/create-t3-app/issues/204 by using the default sqlite database file path as the DATABASE_URL
💯

fix: missing DATABASE_URL

---

package.json
pnpm-lock.yaml
src/consts.ts
src/utils/renderTitle.ts

---
This PR improves the typography of the A's in the ascii logo. It also removes a dependency.
There are two obvious ways to implement this - make the ascii text a const, or read it from an external text file. I decided to make it a const, which is simpler but makes the ascii harder to read in code due to having to escape backslashes. Let me know if you prefer the other solution.
---
top: before, bottom: after
💯

feat: improved logo typography

---

src/cli/index.ts
src/helpers/createProject.ts
src/helpers/initGit.ts
src/helpers/installPackages.ts
src/helpers/logNextSteps.ts
src/helpers/scaffoldProject.ts
src/helpers/selectBoilerplate.ts
src/index.ts
src/installers/envVars.ts
src/installers/index.ts
src/installers/next-auth.ts
src/installers/prisma.ts
src/installers/tailwind.ts
src/installers/trpc.ts
src/utils/getT3Version.ts
src/utils/renderTitle.ts
src/utils/runPkgManagerInstall.ts
tsconfig.json

---
_Summary_
---
close #206 by adding path alias into tsconfig.json

refactor(cli): add module path aliasing

---

template/page-studs/index/with-auth-trpc-tw.tsx
template/page-studs/index/with-trpc-tw.tsx
template/page-studs/index/with-tw.tsx

---
Currently, with Tailwind selected some of the content gets pushed offscreen on small viewports and cannot be scrolled property. I fixed this by changing container height to min-height.
---
Before:
After:
💯

fix: height on small viewports

---

template/base/README.md

Following the same method given in [NextJs examples](https://github.com/vercel/next.js/tree/canary/examples/with-docker)

docs: add instructions on building docker image to readme

---

template/base/README.md

adds subheader, link, collapsable code blocks and syntax hightlighting

docs: small adjustments

---

src/utils/parseNameAndPath.ts

---
resolves https://github.com/t3-oss/create-t3-app/issues/269
Before, when running create-t3-app with '.' as the name argument (ie to init inside the current folder), the `name` in package.json was also set to `.`. With this pr, the folder name is used instead in that case. This is the same behaviour as many other tools such as create-next-app.
💯

feat: set appName to directory on 'npx create-t3-app .'

---

template/addons/prisma/auth-schema.prisma

---
Fixed small typo in auth-schema.prisma (changed @db.text to @db.Text)  to address    #277 
Refrence: https://www.prisma.io/docs/concepts/database-connectors/postgresql
---

fix(prisma): fix minor typo in prisma schema

---

template/addons/next-auth/next-auth.d.ts

---
Resolves https://github.com/t3-oss/create-t3-app/issues/281
Makes `session.user.id` non-nullable, resulting in fewer guard clauses without . For further thoughts see https://github.com/t3-oss/create-t3-app/issues/281.
This changes behaviour that was discussed extensively in https://github.com/t3-oss/create-t3-app/pull/180#issuecomment-1182760580, however in that PR the only options discussed were both user and user.id nullable, or both user and user.id non nullable, not user nullable but user.id non nullable.
Open for comments though :)
---
💯

feat: make session.user.id non-nullable

---

template/addons/next-auth/next-auth.d.ts

---
Main:
https://github.com/t3-oss/create-t3-app/blob/6a81f03bfafdf77c1c82b7972a97e3e54d77935c/template/addons/next-auth/next-auth.d.ts#L7-L11
Next:
https://github.com/t3-oss/create-t3-app/blob/7627d2292c30d8c3027d4e21c530cb6f9de6bf71/template/addons/next-auth/next-auth.d.ts#L7-L11
---

fix: inverse the optional made in #284 to match #282

---

README.md

---
Per a discussion in the tRPC discord server (in the thread at <https://discord.com/channels/867764511159091230/1006027755755946054>), the link to the documentation of the alpha version of tRPC should link to the new alpha docs instead of a temporary README that may be deleted soon.
---
<details>
<summary>Screenshots of thread for archival purposes:</summary>
</details>
💯

docs: update tRPC v10 docs link

---

src/utils/parseNameAndPath.ts

---
https://github.com/t3-oss/create-t3-app/blob/f060d59a4e53a6932c5dd9620a20efa7d1c96241/src/utils/parseNameAndPath.ts#L16-L19
On windows, process.cwd() returns something like: `D:\\path\\to\\project`, which breaks the above code since it uses `\\` instead of `/` to separate efferent segments of path.
Consequently, project generated by `create t3 app` will use an invalid app name:
This PR uses nodejs's builtin path module to parse the path returned by process.cwd() before consuming it, ensures windows users get correct package name.

fix: parse path returned from process.cwd() before using it

---

src/index.ts

---
Same as https://github.com/t3-oss/create-t3-app/pull/305 but on next
---
💯

feat: include ct3a version as metadata (next)

---

.gitignore

chore: ignore package-lock

---

.changeset/clever-pots-pump.md
cli/template/addons/trpc/auth-context.ts
cli/template/addons/trpc/auth-prisma-context.ts
cli/template/addons/trpc/base-context.ts
cli/template/addons/trpc/prisma-context.ts

Superseeds #186
---
cc @KATT
- wrap context in a helper so it's usable in createSSGHelpers (and testing but who cares)
---

feat: wrap createContext in helperfunc to make it independent of req/res

---

.changeset/rude-bags-fetch.md
cli/template/addons/trpc/base-context.ts
cli/template/addons/trpc/prisma-context.ts

---
As of 5.8.0, build fails when selecting only tRPC or tRPC + Prisma:
```
./src/server/router/context.ts
5:29  Error: Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.  @typescript-eslint/ban-types
```
This commit fixes this by replacing the `{}` type with `Record<string, never>` and a comment telling users to use an object if they want to pass things.
An alternative would be to relax the eslint rules, but I think keeping them as they are is better.
💯

fix: build fails on trpc, trpc+prisma

---

.changeset/loud-planets-push.md
cli/template/page-studs/_app/with-auth-trpc.tsx
cli/template/page-studs/_app/with-trpc.tsx

---
The getBaseUrl function was always returning an empty string, i.e. a relative path, because typeof window !== undefined is always true. This PR just changes undefined to the string 'undefined' to fix it.
💯

fix: invalid typeof window comparison to undefined

---

www/src/css/custom.css

---
Currently links are the same color as regular text in the docs. This PR changes them to the already defined `color-primary`.
---
💯

feat: make links in docs a contrasting color

---

.changeset/cyan-bags-sit.md
cli/template/addons/trpc/auth-index-router.ts

<p>
While scaffolding a project with Next Auth and tRPC, there is a `protected-example-router` to show how to protect tRPC routers with Next Auth. This router is merged as `question.` in the index file. But in `src/pages/index.tsx`, the query is called using `auth.getSecretMessage` which will obviously fail because its `question.getSecretMessage`. This PR fixes it and merges the router as `auth.`.
</p>

fix: use auth instead of question while merging the router

---

cli/src/installers/index.ts
cli/src/installers/trpc.ts
cli/template/addons/trpc/auth-index-router.ts
cli/template/addons/trpc/auth-router.ts
cli/template/addons/trpc/example-prisma-router.ts
cli/template/addons/trpc/example-router.ts
cli/template/addons/trpc/index-router.ts
cli/template/addons/trpc/utils.ts

---
- Updates tRPC to alpha-48. This version supports @tanstack/react-query, so made that change too.
- Renamed the server-utils from `utils` -> `trpc` since that's what the tRPC examples are using.
- Removed inference helpers since they are no longer supported. Check docs for how to do this, (it might change).
---
💯

chore: utils->trpc, inferance and v48

---

.changeset/six-bikes-tap.md
cli/template/base/tsconfig.json
package.json

Closes #343 and #342
---
- Adds `cjs` and `mjs` files to the tsconfig so they can be linted and typechecked.
- Removed explicit including `next-auth.d.ts` since it will be picked up by `**/*.ts` and was confusing for people not choosing NextAuth.js as a package. 
- Also added a clean script for convenience.
---
💯

fix: tsconfig include + clean script

---

cli/template/addons/trpc/utils.ts

Closes #296
---
Adds a `loggerLink` for tRPC queries during dev.
---

feat: trpc10 loggerLink

---

.changeset/wise-dolphins-grin.md
cli/src/installers/trpc.ts
cli/template/addons/prisma/client.ts
cli/template/addons/trpc/api-handler-prisma.ts
cli/template/page-studs/_app/with-auth-trpc.tsx
cli/template/page-studs/_app/with-trpc.tsx

Closes #306
---
Finishes what's been started on #312.
💯

feat: add loggers during dev

---

cli/template/base/README.md
www/src/pages/en/deployment/docker.md

---
A few things were still missing in https://github.com/t3-oss/create-t3-app/pull/333
- next.config.mjs links to the file in the repo in a few places
- some suggested changes were accepted but not copied from readme to docs
- a link in docker-compose had whitespace in the middle of it

feat: more updated docker instructions

---

.changeset/breezy-gorillas-beam.md
cli/package.json
cli/src/utils/runPkgManagerInstall.ts
pnpm-lock.yaml

Closes #356
---
When in `noInstallMode`, packages look to be added in the order the `runPkgManagerInstall` function and its options are called.  This leads to eventual diffs if a package manager is ever used, as those tools do this kind of sorting automatically.
This PR uses [`sort-package-json`](https://www.npmjs.com/package/sort-package-json) to sort the resultant `package.json` of a `noInstallMode` similar to how package managers would sort `dependencies` \ `devDependencies`. A drawback is that it also sorts `scripts`. An alternative approach can be to not use this dependency and sort just `pkgJson.dependencies` / `pkgJson.devDependencies`. I went with the easiest for me to implement to start; happy to close if this isn't useful (read contributing guide and I don't think implementing …

chore: Sort `package.json` when in `noInstallMode`

---

www/src/LandingPageComponents/Banner/banner.astro
www/src/LandingPageComponents/Footer/footer.astro
www/src/LandingPageComponents/Navbar/navbar.astro
www/src/LandingPageComponents/Tweets/tweet.astro
www/src/LandingPageComponents/Tweets/tweets.astro
www/src/components/footer/avatarList.astro
www/src/components/header/search.tsx
www/src/components/header/sidebarToggle.tsx
www/src/components/leftSidebar/leftSidebar.astro
www/src/components/pageContent/pageContent.astro
www/src/components/rightSidebar/moreMenu.astro
www/src/components/rightSidebar/tableOfContents.tsx
www/src/layouts/landingPage.astro
www/src/layouts/mainLayout.astro
www/src/styles/global.css
www/src/styles/index.css
www/tailwind.config.cjs

~- [] I performed a functional test on my final commit~
---
---
--
💯

docs: Fix Mobile Menu, Light Mode Updated, Copy to Clipboard Fixed

---

www/src/components/blog/avatarList.astro

---
- the code block for throwing an error if the SNOWPACK_PUBLIC_GITHUB_TOKEN is missing was inaccessible because the value is either equal to the token itself or 'hello', both of which pass a null check
- might be related to https://github.com/t3-oss/create-t3-app/pull/372
---
💯

fix: throw error on missing snowpack github token

---

.changeset/seven-pillows-exercise.md
cli/src/helpers/scaffoldProject.ts

Closes https://github.com/t3-oss/create-t3-app/issues/230
---
- Add another choice to the CLI if there are existing files: continue and overwrite
---
CLI Option:
Each choice:
Scaffolding dir before running CLI (and after aborting):
Scaffolding dir after emptying the folder:
Scaffolding dir after continue and overwriting (package.json is overwritten, `somefile` still exists):
💯

feat: add continue and overwrite option on existing dir

---

README.md

---
The `alpha.` site now redirects to the main site, which by default is the 9.x docs (try in incognito/private window), this change makes it go to the v10 docs
---
💯

docs: update tRPC v10 docs link again

---

cli/src/cli/index.ts

---
Moves some big blocks of code to functions, so the main function can be clearer/easier to read.
💯

refactor(cli): avoids big code blocks

---

www/src/components/navigation/TableOfContents.tsx
www/src/components/navigation/ThemeToggleButton.css
www/src/components/navigation/ThemeToggleButton.tsx
www/src/components/navigation/leftSidebar.astro
www/src/components/navigation/moreMenu.astro
www/src/layouts/blog.astro

---
Wanted to contribute to the new docs and here are some improvements I did. Mostly to do with styling.
- Fixed "On this page" text styles when in light mode
- Added sticky behavior to the sidebars when reading the docs
- Modified "More" text style on right sidebar to be consistent with "On this page" text style
- Added a little more spacing to the headers in left sidebar
- Removed weird behavior where the page would scroll to the top when the user toggled between light theme and dark theme
---
Since the most important changes are visual, I thought I would share some videos instead. You can also feel free to compare with the Preview URLs from Vercel to try out the improvements.
[Current styles without sticky sidebars and weird scroll theme toggle …

docs: minor improvements

---

.changeset/fast-maps-deliver.md
cli/template/page-studs/_app/with-auth-trpc.tsx
cli/template/page-studs/_app/with-trpc.tsx

---
Updated withTRPC#config to include the ctx as it is needed to forward the headers when using ssr.

fix(template): missing ctx when using ssr with trpc

---

www/src/components/blog/avatarList.astro

---
Avatar layout was glitching with 3 icons. Fixed it and simplified the CSS.
---
Before:
After:
💯

fix: contributor avatar layout

---

www/astro.config.mjs
www/src/components/blog/pageContent.astro
www/src/components/headCommon.astro
www/src/components/navigation/ThemeToggleButton.tsx
www/src/components/navigation/leftSidebar.astro
www/src/components/navigation/moreMenu.astro
www/src/components/navigation/navbar.astro
www/src/styles/global.css

---
Addresses [#440](https://github.com/t3-oss/create-t3-app/issues/440)
- Fixed toggle initialization
- Fixed scrollbar on light mode
- Fixed code background on light mode
- Added darker color for hover on sidebar links
---

feat: added light mode back

---

www/src/components/landingPage/banner.astro

---
Fixed GitHub button text color in the website banner component. It is supposed to be white.
---
Before
After
💯

fix: use correct button text color on website banner

---

.changeset/spicy-eyes-cry.md
cli/src/helpers/logNextSteps.ts
cli/src/helpers/scaffoldProject.ts

---
Two small improvements when running the CLI in `.`
- user isn't told to `cd .`
- Say `App scaffolded successfully` instead of `. scaffolded successfully`
Can make the same changes to `next` after this is approved.
---
Top: scaffolding in another folder
Bottom: scaffolding in `.`
💯

feat: better cli text when scaffolding in '.'

---

www/src/components/landingPage/banner.astro
www/src/components/landingPage/community/communityCard.astro
www/src/components/landingPage/stack/card.astro

---
Some components on the landing page had an underline on hover which looked weird.
---
Before
After

fix: remove unnecessary underlines in components on landing page

---

www/src/components/footer/footer.astro
www/src/components/navigation/navbar.astro

I noticed that every single component on the website does have some kind of border-radius to it, except the logo.
I don't expect everyone to like this change but I've created a PR either way.
---
Before
After

feat: round t3 logo on website and docs page

---

www/src/components/navigation/MobileMenu.tsx
www/src/components/navigation/MobileMenuButton.tsx
www/src/components/navigation/Search.tsx
www/src/components/navigation/SidebarToggle.tsx

fix: "invalid hook call" on astro build 

---

www/src/components/blog/pageContent.astro
www/src/components/footer/footer.astro
www/src/components/navigation/leftSidebar.astro
www/src/components/navigation/rightSidebar.astro
www/src/layouts/blog.astro
www/src/styles/global.css

---
- Copied approach of docs layout from [astro.build](https://docs.astro.build/en/getting-started/)
- Fixed scrolling behavior on left sidebar
💯

refactor(blog): rework blog ui and improve scrolling behavior

---

www/src/components/navigation/TableOfContents.tsx

---
Before, active sidebar table of contents becoming bold made the sidebar resize and sometimes overlay the main content.
This fix uses underline instead. 
---
Before:
https://user-images.githubusercontent.com/8353666/190897436-b7aa4897-c2d0-49d2-b54d-a1fe7542d38f.mp4
After:
https://user-images.githubusercontent.com/8353666/190897451-3f9a8fa5-3dc3-441c-b71d-a2d1abc82843.mp4
💯

fix: docs right sidebar overlaying content

---

.github/workflows/ci.yml
www/src/components/landingPage/tweets/tweetSlider.tsx
www/src/components/landingPage/tweets/tweets.astro
www/src/components/landingPage/tweets/types.ts

---
Improves setup when not provided a Twitter API Key
---
💯

fix: add ci mode to tweetwall

---

cli/src/installers/index.ts

---
temporarily pins next-auth to 4.10
this is because 4.11+ has next 12.2.5 as a peer dep, and we are on 12.3.1
💯

fix: temp pin next-auth to 4.10 due to peer deps (next)

---

www/src/components/landingPage/cli.tsx

Fixes the cli font size on small devices.
The text is pretty small on smartphones now, though. The only alternative I can think of would be to hide the terminal for phone screens smaller than sm.

fix: terminal font size on small devices

---

www/src/components/landingPage/stack/card.astro

Removes underlines when a card link has been clicked on.

fix: card link text underline

---

www/src/pages/en/usage/typescript.md

Fixes the quote on the typescript docs page
---
before
after

fix: typescript docs quote

---

CONTRIBUTING.md

---
Fixed wrong path to changeset folder on commit step of contributing
---

docs(contributing): fix typo in changeset commit step

---

.github/workflows/ci-labeler.yml
.github/workflows/ci.yml

---
- fix labeler breaking on pr from external branch
- split ci into two action groups
💯

fix: two ci action groups (test)

---

www/src/components/footer/footer.astro
www/src/layouts/docs.astro

---
- Previously the footer didn't stick to the bottom in docs pages that are smaller than screen height, now it does
- Also reduced the somewhat ridiculous spacing in it a bit
---
Before: 
After: 
💯

feat: docs footer sticks to bottom and is smaller

---

.vscode/settings.json

Looks like VSCode didn't autorun prettier on certain files with the prev glob-pattern

chore: extend glob patterns

---

.github/pull_request_template.md

---
Updates the date above to today
---
💯

chore: update `updated_at` on pr template

---

.changeset/purple-plums-approve.md
cli/src/installers/index.ts
cli/src/installers/tailwind.ts
cli/template/base/package.json

---
No real need to install prettier in the base application - goes against the `you can npm install it` so moved it to the tailwind installer so it's only installed alongside the tailwind-plugin.
---
💯

feat: remove prettier from base

---

.changeset/tender-ducks-mate.md
cli/src/installers/envVars.ts

Closes #585
---
IIRC we only generated `.env-example` a while ago, and changed it to `.env` so that the app could be immediately started after scaffolding. Will close this PR if anyone has a good reason why we shouldn't include both `.env` and `.env-example` by default.
---
- Creates a `.env-example` file with the same content as the normal `.env` file plus a warning about not putting secrets in there.
- Moves the `if (!envFile) return;` guard clause up a few lines to prevent pointlessly generating the envContent before not saving it to anywhere.
---
💯

feat: add .env-example

---

.changeset/two-cows-brake.md
cli/src/installers/index.ts

Related issue/pr: #504 #505 #506
Removes version lock of next-auth since they no-longer have the strict peerDep of `next@12.2.5`. 
See https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.12.1

fix: remove version lock on nextauth

---

.changeset/poor-pants-rhyme.md
cli/template/base/README.md

---
Really feel like I should just push directly but I made a PR anyway
---

chore(template): remove the mention of @next in template readme

---

www/src/components/navigation/sidebarToggle.astro
www/src/styles/global.css

Closes #555
---
- change `word-wrap: break-word;` to `overflow-wrap: anywhere` to allow the links in the reference table to wrap by breaking words, stopping them from breaking the layout
- add `height: 100vh;` to `.mobile-sidebar-toggle`, together with the existing `overflow: hidden` property to prevent scrolling when the mobile sidebar is opened
- move the `.mobile-sidebar-toggle` class toggle up from `body` to `html`, to prevent scrolling on the home page when the mobile sidebar is opened
---
- Both before and after changes images are taken at the bottom of page `/en/deployment/docker`, first without opening the mobile menu then after opening it.
💯

fix(docs): fix mobile layout issues

---

.changeset/loud-ways-flash.md
cli/src/installers/index.ts
cli/template/addons/trpc/auth-context.ts
cli/template/addons/trpc/auth-index-router.ts
cli/template/addons/trpc/auth-prisma-context.ts
cli/template/addons/trpc/auth-router.ts
cli/template/addons/trpc/auth-server-utils.ts
cli/template/addons/trpc/example-prisma-router.ts
cli/template/addons/trpc/example-router.ts
cli/template/addons/trpc/index-router.ts
cli/template/addons/trpc/prisma-context.ts
cli/template/addons/trpc/server-utils.ts

---
`t` is often used for translation stuff so importing it as your trpc object may feel weird. This is another way of using trpc v10 in that we define all our "base"-procedures and stuff in one file and import those, instead of the entire `t`-object.
Goes inline with the authedProcedure too btw.
Leave your thoughts, I'm just putting it out there. Happy to close if y'all don't like it.
---
💯

feat: align trpc usage to official docs

---

www/src/styles/global.css

---
Add `vertical-align: top` to `.markdown table > tbody > tr > td` to align table text on top instead of center.
---
💯

docs: top-align table items

---

.changeset/spicy-falcons-poke.md
cli/template/addons/trpc/utils.ts

Closes #612
---
cc @nick1n
Export InferenceHelper and show example usage
---
💯

feat(t3-app): add inference helper and example usage

---

www/src/components/headCommon.astro
www/src/components/landingPage/cli.tsx

---
Currently, the cli simulation has missing characters on some Android devices (possibly also other OSs?) in the 'A' of the ascii text. This fixes it.
---
Apologies for the photos, I just borrowed this Android device and don't have anything set up on it
Before:
After:
💯

fix: missing characters in homepage cli on android

---

.changeset/real-panthers-compete.md
cli/package.json
cli/src/helpers/git.ts
cli/src/helpers/installDependencies.ts
cli/src/index.ts
pnpm-lock.yaml

Closes #610
---
Installde `execa` to exec loader asynchronously.
---

fix(cli): make loader async to make it spin

---

.changeset/wise-toys-fry.md
cli/src/helpers/git.ts

---
hopefully fixes the git spinner? leaving as draft for now
💯

fix: git spinner

---

.changeset/hot-stingrays-live.md
cli/template/addons/prisma/auth-schema.prisma
cli/template/addons/prisma/schema.prisma

Closes #618 
---
Added `createdAt` and `updatedAt` to Example prisma model.

feat(template): add createdAt and updatedAt to example model

---

www/src/components/headSeo.astro

---
Use `Astro.url.origin` to build the path to OG Image.

fix: use url.original to build og image path

---

.changeset/loud-planets-breathe.md
cli/src/cli/index.ts
cli/src/helpers/installDependencies.ts
cli/src/installers/nextAuth.ts
cli/template/addons/next-auth/_npmrc
cli/template/addons/next-auth/_yarnrc

---
- If the user is on node 18 and chooses to install during cli, `--ignore-engines true` (yarn) or `--engines-strict false` (npm or pnpm) is used
- If next-auth is selected, `.npmrc` and `.yarnrc` files with the same flags are created, regardless of what node version the user is currently on
- FIXME's linking to [the next-auth issue](https://github.com/nextauthjs/next-auth/issues/4575) so that we can hopefully get rid of this again ASAP. I'm also subscribed to the issue.
- Tested with current versions of npm, yarn classic, and pnpm
I don't love doing this and could also see the argument for just leaving next-auth not working on node 18 until they release a fix, but personally I'm leaning towards this (not great) solution for the time being. 
I'd also appreciate a Windows user confirming …

fix: next-auth doesn't install when using node 18

---

www/src/pages/en/usage/next-js.md

---
Fixed the link in the Usage of NextJS section of the docs to Incremental Static Regeneration. Added data-fetching/ subroute into the link so it's no longer broken.
---
💯

docs: fix broken link to NextJS docs

---

www/src/components/navigation/githubIcon.astro

---
Make the gh icon arrow have consistent color with the container border.
---
Dark theme:
Dark theme hover:
Light theme:
💯

fix: gh icon arrow to have same color with container border

---

CONTRIBUTING.md

Standardize prerequisites verbiage to be singular and not plural.
---
Updates `changes` (plural) to `a change` (singular) to match the rest of the Prerequisites paragraph.
---
💯

docs: Contribution guidelines gramatical update

---

.changeset/pretty-shrimps-behave.md
cli/src/installers/envVars.ts

---
Adds a short comment on .env to document some ways to generate NEXTAUTH_SECRET and a short reference to related link in Next-Auth docs.
---
💯

docs: add documentation on generating NEXTAUTH_SECRET on generated .env

---

.changeset/unlucky-clocks-report.md
cli/template/page-studs/index/with-auth-trpc-tw.tsx
cli/template/page-studs/index/with-auth-trpc.tsx

---
A lot of people seem to be confused that there are tRPC errors in the console as soon as they open their app
Example (there have been a bunch of these): https://discord.com/channels/966627436387266600/1020552951116333217/threads/1030282705734226051
This avoids those errors by only enabling the query if there is a user. As a nice benefit it also acts as builtin documentation for passing `undefined` for the input and using the `enabled` option.
---
(taken after starting the dev server and navigating to localhost:3000 without being logged in)
Before:
After:
💯

feat: AuthShowcase only makes query when logged in

---

.changeset/afraid-news-fail.md
cli/template/base/package.json

---
- updated next to 13.0.1
---

feat: update to next 13.0.1

---

.changeset/little-badgers-cheat.md
.github/workflows/e2e.yml
cli/src/cli/index.ts
www/src/pages/en/installation.md

Closes #652 
---
Fixed tailwind flag typo in help command
---

fix: tailwind is a boolean

---

www/src/components/navigation/tableOfContents.astro

---
In the create t3 app docs website the table of contents active link was not showing properly as you can see in first video.
Fixed that issue in second video.
Open for any feedback and improvements.
---
Not working example video
[table-content-active-link-not-showing-properly.webm](https://user-images.githubusercontent.com/62164346/199393037-3f000112-b1f2-4595-9341-a4d526963c9c.webm)
Working video demo
[working-active-link-of-table-contents.webm](https://user-images.githubusercontent.com/62164346/199393798-2459ffba-fbdf-48a4-be87-2499434a75cb.webm)
💯

fix: table content active link not showing properly

---

cli/template/base/src/pages/index.tsx
cli/template/page-studs/index/with-auth-trpc-tw.tsx
cli/template/page-studs/index/with-auth-trpc.tsx
cli/template/page-studs/index/with-trpc-tw.tsx
cli/template/page-studs/index/with-trpc.tsx
cli/template/page-studs/index/with-tw.tsx

---
When selecting NextAuth the boilerplate uses React.FC on the AuthShowcase component
```typescript
const AuthShowcase: React.FC = () => {
...
}
```
But the TechnologyCard component doesn't.
---
💯

refactor: consistent use of React.FC

---

www/src/layouts/landingPage.astro

Closes #677
---
Fixes the screen being wider than the background image.
---
Here's what happens: (I removed the reduced opacity so it's clearer to see the issue)
💯

fix: landing page background image max width

---

cli/src/cli/index.ts
cli/src/helpers/installDependencies.ts
cli/src/helpers/logNextSteps.ts

updated variable naming for consistency; moved changes from #681 to this one due to issues with my local repo desyncing
Closes #678 
---
--- Fixed yarn to use default behavior when invoking `yarn`, which is to install dependencies
--- Updated the output of the CLI to reflect the differences in the package manager commands of yarn and not-yarn to better inform the user
**pnpm install**
**yarn start with user wanting to run yarn**
**yarn start with user not wanting to run yarn through cli**
💯

fix(cli): fix create-t3-app to use yarn default behavior (#678)

---

.changeset/seven-eggs-vanish.md
www/src/styles/global.css

Closes #692
---
The word break on list elements was set to 'normal' so on small and medium devices docs body was wider then nav. 
Now the word-break stays the same on large screens but on small and medium its set to `break-all`
---
Before:
Now: 
💯

fix(docs): fixed list styling issue on sm/md screens.

---

www/src/pages/en/faq.md
www/src/pages/en/installation.md
www/src/pages/en/usage/next-auth.md

---
- Replace all `Next-Auth` with `NextAuth`
- Replace all `Next-Auth.js` with `NextAuth.js`
Why omit the `-`? PFB.
---
💯

fix(docs): consistent use of `NextAuth` / `NextAuth.js`

---

www/src/config.ts
www/src/pages/en/usage/first-steps.md
www/src/styles/global.css

---
- Add "first steps" page to the docs (let me know how yall feel about this - I made it because I think it would be good to have a link to a "everything you need for db and auth to work" page in the template index.tsx)
- Reduce the ridiculous h3 top margin
💯

docs: add "first steps" page and reduce h3 spacing

---

www/src/components/navigation/moreMenu.astro

Closes #706
---
1. Removed the `Edit this page` link in mobile view to give the footer a _clean_ look. Astro [docs](https://docs.astro.build/en/getting-started/) does the same. Thoughts?
2. Reworded the link text
---
- Desktop View
- Mobile View
💯

docs: better "more" menu on mobile

---

www/src/components/navigation/leftSidebar.astro
www/src/components/navigation/moreMenu.astro
www/src/components/navigation/navbar.astro
www/src/components/navigation/tableOfContents.astro
www/src/styles/global.css

Closes #720
---
* Updated the text color of the left navigation links from `text-t3-purple-400` to `text-t3-purple-800`. 
* Updated the text color of the top navigation links from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`. This is just for consistency. 
* Updated the text color of `Table of Contents` from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`.
* Updated the text color of `More` from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`.
---
Before:
After:
💯

docs: increase the contrast of navigation links' text color against the background color. 

---

www/src/components/navigation/leftSidebar.astro
www/src/layouts/docs.astro

Closes #723 
---
Fix to #723: Custom scrollbars are not displayed on Firefox (see screenshot).
OS: Windows.
---
Problem:
Update:
💯

docs: bug - firefox doesn't always use custom scrollbars

---

.changeset/warm-sheep-suffer.md
cli/src/cli/index.ts
cli/src/index.ts
cli/src/utils/renderVersionWarning.ts

feat: render warning when using a tagged or outdated version

---

www/src/pages/en/usage/trpc.md

---
The signature for `setData` has changed. This commit will do two things:
- Provide `undefined` for the input argument (mandatory).
- Use the updater function (`old => [...old, newPost ]`) instead of the `prevData` directly. This makes it also align with the React Query docs:

docs(tRPC): Switch to new `setData` signature

---

www/src/components/landingPage/stack/stack.astro
www/src/pages/en/introduction.md

---
- TailwindCSS => Tailwind CSS in landing page stack
- Added a space after `...` to decongest.
- there's => there're. Lemme know if that's alright, will revert otherwise. 
- Before
- After 
- Before 
- After 
💯

docs: minor fixes

---

www/src/components/navigation/themeToggleButton.astro
www/src/layouts/docs.astro

Closes #738
---
Prevent applying of global transitions
Remove transition duration for Theme Toggle
---
Before:
https://user-images.githubusercontent.com/3381481/202189087-f8749ba9-b495-475d-a5aa-45a96d76ad31.mp4
After:
https://user-images.githubusercontent.com/3381481/202189122-f3705922-c9f7-4067-bef2-c20e48eb18b1.mp4
I could only replicate the issue seen on the [Docs](https://beta.create.t3.gg/en/introduction) when running `pnpm build` and `pnpm preview` from `/www`
For reasons beyond my small brain, I could not replicate with `pnpm build:www` running from root.
💯

fix: layout shift on docs

---

www/src/pages/en/faq.md

---
Added an FAQ item responding to the common question of "Why aren't you using the `/app` folder from Next.js 13??".
---
💯

docs: add "why not `/app`?" FAQ

---

.changeset/thick-yaks-exist.md
cli/template/page-studs/index/with-auth-trpc-tw.tsx
cli/template/page-studs/index/with-auth-trpc.tsx

---
Removed the optional chaining on `sessionData`. It is already verified at the start of the line.
---
💯

fix: removing redundant optional chaining in templates

---

.changeset/five-tigers-double.md
cli/template/base/_gitignore

---
Added `next-env.d.ts` to `.gitignore` as recommended in Next.js [documentation](https://nextjs.org/docs/basic-features/typescript).
---
💯

chore: ignore next-env.d.ts

---

www/src/components/navigation/themeToggleButton.astro

Closes #781 
---
Refactored themeToggleButton to use a `<button>` root element instead of 2 radio buttons so that the light/dark theme gets toggled regardless of where the user presses within the component.
The component's `title`, `value` and `aria-label` attributes gets set on page-load using the appropriate dark/light state.
---
💯

docs: made themeToggleButton a toggle button

---

www/src/components/landingPage/tweets/tweetSlider.astro

---
Fixed issue with tweet slider pausing permanently after hover
---
💯

fix: tweet slider pausing permanently on hover

---

www/src/layouts/docs.astro

---
The scrollbars of the right nav and the body were overlapping on some screen sizes. Fixed this by adding a spacer that shifts the right nav when necessary. The scrollbar now lines up with the end of the search box above it at all screen sizes.
---
Before:
After:
💯

fix: overlapping scrollbars in docs

---

.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

- uses new output api
- updates to use node 18 in ci
These warnings are now gone:

chore(ci): use new output api

---

www/src/pages/en/usage/typescript.md

---
Changed "Avatar of @alexdotjs" to "Avatar of @t3dotgg" in the "alt" attribute for Theo's profile picture on TypeScript page.
---
💯

fix(docs): Fixed wrong alt attribute

---

cli/template/addons/next-auth/get-server-auth-session.ts

This is a trivial style fix. Third party library imports are grouped apart from local imports throughout the project, I guess this file shouldn't be an exception.
---
_[Not required]_
---
_[Not required]_
💯

fix(style): imports grouping, trivial

---

www/src/layouts/landingPage.astro

---
Display the background pattern via a pseudo-element bg-image instead of an image tag. Fixes unnecessary whitespace on specific screen sizes
---
**Current**:
**Changed**:
💯

fix: extra whitespace on landing page

---

www/src/pages/en/faq.md

Suggestion from @juliusmarminge : https://github.com/nramkissoon/t3-stripe/issues/1
Added to FAQ articles because that section is more focused on tutorials.
---
---
💯

docs: add T3 Stripe article to FAQ articles

---

www/src/pages/en/folder-structure.md

---
Updated the spelling of tailwind in the folder structure docs.
---
💯

docs: Fix spelling of Tailwind in folder-structure.md

---

www/src/components/navigation/LanguageSelect.tsx

---
- Improved the language select dropdown animation
- Removed margin top from language select button that made it look asymmetrical
- Added a border to the language select dropdown in dark mode
- Increased padding of the language select dropdown to make it look less narrow (I'm not sure if this looks good or not, tell me if it doesn't and I'll remove it 👍)
From (Notice how the language select button is not properly aligned with the rest of the buttons in the header. It has a slight margin top)
To

docs: improve language select styling

---

www/src/styles/global.css

---
#867 removed scroll padding from the page, now when you open a link with a hash to a specific section of the page (for example https://create.t3.gg/en/introduction#the-t3-stack) the heading of the section is hidden behind the header. This PR fixes that without breaking the language selector.
---
💯

fix(docs): added scroll-margin to headings

---

.changeset/early-coats-stare.md
cli/template/base/_gitignore
www/src/pages/en/usage/env-variables.md

Closes #304 
---
Add a note about opinions surrounding `.env` files and the reason for the departure from next's oppinions.

docs: add notes about env vars

---

www/astro.config.mjs
www/src/styles/global.css

was brought up in another pr that we should mark external links.
not sure if I like it or not myself

docs(RFC): external link glyph

---

.changeset/late-beds-jump.md
cli/src/helpers/git.ts

---
Introduced new function `getDefaultBranch()` in `./cli/src/helpers/git.ts`, which either returns the default branch name configured on the users computer or `main`.
Said function is called everytime the user decides to automatically initialize a git repository to set the default branch
---
💯

feat: using 'init.defaultBranch' when initializing git repo

---

www/src/components/docs/breadCrumbs.tsx
www/src/config.ts

---
- Made breadcrumbs work on non-English pages. Translations are pulled from `config.ts` file.
- Fixed React warnings in `breadCrumbs.tsx`
---
**BEFORE**
**AFTER**
💯

fix: breadcrumbs translations

---

.changeset/few-mangos-clean.md
cli/src/installers/index.ts

---
Pins next-auth to 4.17.0 and @next-auth/prisma-adapter to 1.0.5 until we fix the problems that we have due to breaking changes in 4.18
💯

fix: (temp) pin next-auth

---

.github/workflows/ci.yml

Seems like we make too many requests during CI for the token to handle:
Removing the token will make sure we don't fetch at all

chore(ci): prevent rate-limiting

---

www/src/components/docs/pagination.astro

---
The language code was hardcoded to `EN` before in pagination. Updated the file so that pagination works for all languages now.
---
- Prod 
- Now
💯

fix(docs): show pagination on non-EN pages

---

www/src/components/docs/breadCrumbs.tsx
www/src/components/docs/outdatedDocsBanner.astro
www/src/components/docs/pageContent.astro
www/src/components/navigation/OnThisPageLinks.tsx

Also closes #907
---
- all the elements in docs pages have consistent horizontal padding.
- fixed the broken regex for getting `en` link in outdated page banner.
---
💯

refactor(www): consistent spacing in mobile layout

---

www/src/config.ts

---
- Removed flags from languages in docs
- The language select menu looks a bit less nice, but it's a worthwhile tradeoff imo
There is no 1:1 correlation between countries and languages, and using flags to represent languages can imply taking sides in various political conflicts.
Examples:
- Russian is spoken in both Russia and Ukraine
- Arabic is spoken in many countries, and some countries where Arabic is spoken also have large populations of speakers of other languages
- We only have one Portuguese translation, which will be used by people in both Brazil and Portugal
- What language is associated with this flag: 🇮🇳?
- etc
Examples of other docs that don't use flags to denote languages:
- [React](https://reactjs.org/languages)
- [Vue](https://vuejs.org/guide/introduction.html)
- …

docs: remove flags from languages

---

.changeset/lucky-kangaroos-tickle.md
cli/src/installers/index.ts
cli/template/addons/next-auth/get-server-auth-session.ts
www/src/pages/en/usage/next-auth.md
www/src/pages/ru/usage/next-auth.md

Closes https://github.com/t3-oss/create-t3-app/issues/911
---
- spread authOptions into a new object to fix unstable_getServerSession error
- this is probably not the best possible solution so added a FIXME
- unpin next-auth
- update docs & fix outdated naming (`nextAuthOptions` instead of `authOptions`)
---
💯

fix: breaking error caused by unstable_getServerSession changes in next-auth 4.18

---

.changeset/hip-apples-hunt.md
cli/src/installers/index.ts
cli/template/addons/next-auth/get-server-auth-session.ts
www/src/pages/en/usage/next-auth.md
www/src/pages/ru/usage/next-auth.md

---
- upgrade next-auth to `^4.18.3`
- undo the authOptions spreading hotfix
- update docs accordingly
References:
https://github.com/nextauthjs/next-auth/pull/5973
https://github.com/t3-oss/create-t3-app/pull/932#issuecomment-1341907346
---
💯

fix: use next-auth 4.18.3 and undo hotfix

---

www/src/components/navigation/OnThisPageLinks.tsx

---
The `On this page` button cuts off when the page is scrolled up on mobile.
- Before
- After
---
💯

fix(docs): `On this page` button spacing

---

www/src/components/navigation/moreMenu.astro
www/src/components/navigation/navbar.astro

---
The active language selector was hard coded before to `EN`. Updated the code so that the active option syncs with the current language.
- Before
- After
💯

fix(docs): Language selector showing `EN` as active language on `non-EN` pages

---

www/src/components/docs/outdatedDocsBanner.astro

---
- fixes the "this is x days older than the english version" message being incorrect
- it was using the absolute value of the difference in age, ie the foreign version was ALWAYS older
---
en:
pt:
💯

fix: docs translation date diff

---

www/src/components/docs/breadCrumbs.tsx
www/src/components/docs/pageContent.astro
www/src/components/navigation/OnThisPageLinks.tsx
www/src/languages.ts
www/src/pages/ar/usage/env-variables.md

---
Fixes for RTL
- breadcrumbs arrows pointing the wrong way
- "on this page" arrow pointing the wrong way
- "on this page" popover having bad spacing and scrollbar on the wrong side
- env vars folder structure ┫character pointing the wrong way
---
💯

fix: rtl breadcrumbs, "on this page", env var folder structure

---

www/src/components/docs/breadCrumbs.tsx
www/src/components/docs/pageContent.astro

Closes #958 
Closes #959
---
- Breadcrumbs now work when there is a hash in the url (they now use `location.pathname` instead of `location.href`)
- Removed layout shift when they load
---
💯

fix: breadcrumbs fix

---

www/src/pages/ar/deployment/docker.md
www/src/pages/en/deployment/docker.md
www/src/pages/pt/deployment/docker.md
www/src/pages/ru/deployment/docker.md

prisma compiling in a dockerfile has stopped working as per https://github.com/prisma/prisma/issues/14073 and a resolution has been posted, so for now might be a good idea to ensure the website documentation works for dockerfiles
---
applied patch to ensure dockerfile building works again
---
💯

fix(docs): Update-dockerfile to resolve prisma bug

---

www/src/components/navigation/leftSidebar.astro
www/src/languages.ts

we should support different versions of languages such as `zh-cn`,`zh-tw`,` pt-br`
---
- `langPathRegex` should allow lower case letters, like
[astro](https://github.com/withastro/docs/blob/main/src/i18n/languages.ts)
- Corrected the link matching of sidebar, the length of language code can be more than two 
---
💯

fix(docs): correction of language matching

---

www/src/pages/ar/usage/trpc.md
www/src/pages/en/usage/trpc.md
www/src/pages/pt/usage/trpc.md

---
Extremely minor change. Just removed some params in an URL that were probably not intended to be there.
---
💯

docs: remove url params unintentionally included

---

www/src/pages/en/usage/next-auth.md

Use of await inside the `me` protectedProcedure requires the query to be async.
---
---
💯

fix: missing async keyword

---

.changeset/quiet-windows-leave.md
cli/src/cli/index.ts

Duh.
Also, NextAuth.js, but not for much longer. https://twitter.com/balazsorban44/status/1603119547313274883

fix: TS first

---

www/src/languages.ts

make `langPathRegex` can match `zh-hans` and `arc` from rtlLanguages
---
---
💯

fix(docs): correction of langCode matching

---

www/astro.config.mjs

---
On the docs site, all tailwind base styles were included twice in the bundled .css files. First are added by the tailwind astro integration, second by `@tailwind base` line in `global.css`.
This PR adds a config to the astro integration to fix that.
---
💯

fix: tailwind base styles are duplicated

---

www/src/pages/ar/deployment/docker.md
www/src/pages/en/deployment/docker.md
www/src/pages/fr/deployment/docker.md
www/src/pages/no/deployment/docker.md
www/src/pages/pt/deployment/docker.md
www/src/pages/ru/deployment/docker.md
www/src/pages/zh-hans/deployment/docker.md

---
- Recommend `node:16-alpine3.16` as a base image for Docker, as per issue #975
- Affects all translations
💯

docs: recommend `node:16-alpine3.16`

---

www/src/pages/en/folder-structure.mdx

---
I think the content inside the parentheses were added, to give an indication of what to expect when selecting the `--prisma`, and `--nextAuth` flags. Because of the existences of the selector, these two can go.
---
💯

chore: remove redundant content in folder structure file

---

.changeset/proud-rabbits-film.md
cli/src/installers/index.ts
cli/src/installers/tailwind.ts

Closes  #1009
---
`@types/prettier` is now added as a dependency to the project when the Tailwind addon is selected, this ensures auto-completion in the Prettier config file in VS Code after a fresh project init.
---
💯

chore(template): add @types/prettier package to tailwind installer

---

www/src/styles/global.css

Co-authored-by: Julius Marminge <julius0216@outlook.com>
Closes #<1014>
---
- Revert the icon in RTL layout
- Used the `[dir='rtl']` attribute, and used selector to hide it in the devtools.
---
💯

fix: revert link icon in RTL layout

---

www/src/pages/en/deployment/docker.md

Closes #975 
---
- Add a note explaining the rationale for recommending Alpine 3.16, while presenting an alternative solution for using Alpine 3.17 based images.
💯

docs: add note explaining the rationale for Alpine 3.16

---

.github/workflows/prerelease-comment.yml

---
I think most of us (us as in us who test the beta) use `pnpm` nowadays so makes sense to use it for the beta comment. Too lazy to edit it every time and I want to use my pnpm cache when downloading packages :)
---
💯

chore(ci): use pnpm for beta-release comment

---

.changeset/green-laws-hammer.md
cli/src/helpers/scaffoldProject.ts

Closes #1033
Closes #1029
---
- Exits with error code if aborted
- Removed log `<dirname> exists but is empty, continuing...` if scaffolded in current directory.
---
💯

fix(cli): exit with error code when aborting installation

---

cli/template/extras/src/pages/api/auth/[...nextauth]/base.ts
cli/template/extras/src/pages/api/auth/[...nextauth]/with-prisma.ts

---
Easier to close the other branch than trying to resolve v7 merge conflicts in there
We frequently get questions on Discord and other places from people who swap the Discord provider for GitHub or some other one, and then don't understand why their auth is broken. Adding a comment to tell them that they need to look up how each provider works.
No changeset bc no change to functionality
💯

feat: add comment about other providers to next-auth API handler (v7)

---

.changeset/pink-rabbits-fetch.md
cli/src/index.ts

Closes #1053 
---
`name` attribute doesn't get replaced with the project name in `package-lock.json`. Now it does.
---

fix: update name prop before installing deps

---

.changeset/neat-singers-teach.md
cli/src/installers/dependencyVersionMap.ts
cli/template/extras/src/server/api/trpc/base.ts
cli/template/extras/src/server/api/trpc/with-auth-prisma.ts
cli/template/extras/src/server/api/trpc/with-auth.ts
cli/template/extras/src/server/api/trpc/with-prisma.ts

---
Made this addition in trpc 10.8: https://github.com/trpc/trpc/pull/3495
Cleans things up a bit not having to use `Awaited<ReturnType<>>`
---
💯

fix: cleanup context type in `initTRPC`

---

www/src/components/landingPage/stack/card.astro

---
On "ONLY the parts you need" section those card's are taking extra height
and card are hovered (+clickable) while cursor are not on those card.
---
💯

fix: "ONLY the parts you need" card height css

---

www/src/components/docs/pageContent.astro

---
Before this fix, the inline code blocks were wrapped in a `div`, so they were placed on new lines. These line breaks made the documentation harder to read, so I applied the `inline-block` TW classes to them (could've been `inline` too, but I thought that maybe the `block`-aspect of the positioning is important, otherwise a `span`-element would've been used).
---
**Before**
**After**
💯

fix(doc): a styling issue of the inline code blocks

---

www/src/components/docs/pageContent.astro
www/src/styles/global.css

---
the `:has()` selector is not yet enabled in FireFox by default, see: https://caniuse.com/css-has
so instead this PR applies a class to the code wrapper div and styles that. tested in both ltr and rtl.
---
💯

fix: code wrapper not applying styles in firefox

---

www/src/components/docs/pageContent.astro

Fixes #1100 (which is currently closed, but not entirely fixed: https://github.com/t3-oss/create-t3-app/issues/1100#issuecomment-1398209883)
---
#1102 accidentally broke the styling of the code blocks (`code` elements inside of `pre`), because of a broken selector.
This part in `www/src/components/docs/pageContent.astro` selects **all** code blocks (including the children of `pre` elements) and applies the `.code-wrapper` class to them, hence the light background and double border:
```typescript
const notACodeBlock = ":not(pre) code";
const codeElements = document.querySelectorAll(notACodeBlock);
```
#1102 is a good fix to the issue it addressed btw, the was already broken. ☺️ 
---
**Before**
**After**
https://create.t3.gg/en/usage/prisma#seeding-your-database
💯

fix(doc): Fix the broken styling of the code blocks

---

www/src/pages/ar/folder-structure.mdx
www/src/pages/en/folder-structure.mdx
www/src/pages/fr/folder-structure.mdx
www/src/pages/pl/folder-structure.mdx
www/src/pages/ru/folder-structure.mdx
www/src/pages/zh-hans/folder-structure.mdx

---
Updates frontmatter of `.mdx` markdown files so that the footer fetches and links to correct github page.
💯

fix: fetch contributors from correct path

---

www/src/pages/en/usage/trpc.md

---
- Rearrange the tRPC page docs page to show "how it works" before "where are the files". This flow is more helpful imo.
- Add my "How tRPC really works" video
💯

docs: reorder trpc page and add video

---

www/src/components/navigation/githubIcon.astro

---
The current PR aims to use punctuation and format the GitHub stars counter in order to reduce ambiguity and improve readability and comprehension as reported in the [_Web Accessibility Initiative (WAI)_](https://www.w3.org/WAI/)
---
| **Before** |<img width="1276" alt="Screenshot 2023-01-26 at 01 23 34" src="https://user-images.githubusercontent.com/16477661/214726126-9d5cd6cb-e576-4f92-90de-2f0ec20d1e4d.png">|
|---|:---:|
| **After** |<img width="1276" alt="Screenshot 2023-01-26 at 01 23 23" src="https://user-images.githubusercontent.com/16477661/214726168-91b73af0-80ff-47f9-8567-4c7cfbf732bb.png">|
💯

fix: improve readability of gh stars counter

---

www/src/pages/en/usage/trpc.md

---
Updated a reference to the variable `api` contained in the code excerpt that precedes this paragraph of the docs. The variable  used to be name `trpc` before #934 (more specifically, [here](https://github.com/t3-oss/create-t3-app/commit/c20ec705a6d3d3005da24d072cc9be04370ab822#diff-ae1b9bcd2d5f027ac5d93cfa1cf271a8955c052f3beb157b0aa89cc465e391ecL117)).
💯

fix: update renamed variable in the tRPC Usage page

---

.changeset/nasty-points-warn.md
cli/template/extras/src/server/api/trpc/with-auth-prisma.ts
cli/template/extras/src/server/api/trpc/with-auth.ts
www/src/pages/ar/usage/next-auth.md
www/src/pages/en/usage/next-auth.md
www/src/pages/fr/usage/next-auth.md
www/src/pages/no/usage/next-auth.md
www/src/pages/pl/usage/next-auth.md
www/src/pages/pt/usage/next-auth.md
www/src/pages/ru/usage/next-auth.md
www/src/pages/zh-hans/usage/next-auth.md

Closes #1154 
---
Update `unstable_getServerSession` to `getServerSession`. Note: I wasn't sure about updating the `next-auth` provider to `4.19.1` which has a fix for the `getServerSession` type, but I thought there might be a different way to update packages to I opted to not include that.
---
💯

fix: update unstable_getServerSession to getServerSession

---

.github/workflows/translations.yml
cli/template/base/src/env/client.mjs
cli/template/base/src/env/schema.mjs
cli/template/base/src/env/server.mjs
cli/template/extras/src/env/schema/with-auth-prisma.mjs
cli/template/extras/src/env/schema/with-auth.mjs
cli/template/extras/src/env/schema/with-prisma.mjs
cli/tsconfig.json
www/src/pages/en/faq.md

Closes #1149
---
Addressing issue #1149 . Removed the @ts-check comment in js / mjs files in the cli folder in favor of the checkJs option in tsconfig.json. Better follows DRY principles and more strictly enforces typesafety.
---
💯

fix: swapped ts-check comments to checkJs in tsconfig

---

www/src/components/landingPage/pageSection.astro
www/src/components/landingPage/tweets/tweetSlider.astro
www/src/components/navigation/githubIcon.astro
www/src/components/navigation/leftSidebar.astro
www/src/components/navigation/moreMenu.astro
www/src/components/navigation/navbar.astro
www/src/components/navigation/sidebarToggle.astro
www/src/components/navigation/tableOfContents.astro

---
Use astro's built-in `class:list` instead of `clsx` in astro components. React components still use `clsx`.
---
💯

feat: use `class:list` instead of `clsx` in astro components

---

.gitignore

This commit removes a duplicate gitignore declaration.  `.turbo` is declared and grouped ideologically with .vercel on line 48.
This change has no functional effect on stability.  It is just a maintenance contribution.
An alternative to this fix would be to move .vercel into the MISC subset and remove line 48, whichever would be maintainers' preference.

chore: housekeeping in .gitignore

---

www/TRANSLATIONS.md
www/vercel.json

The link to the discord channel was redirecting to the wrong URL.
---
I changed the discord link on https://github.com/t3-oss/create-t3-app/edit/next/www/TRANSLATIONS.md to the correct one.
---

fix: wrong link

---

.codesandbox/tasks.json
CONTRIBUTING.md

This PR adds the edit with codesandbox option for contributing to create-T3-app. The benefits of this includes having :
- Setting up repository in codesandbox in seconds as shown in Screen recoding 
- Seemless branching and main branch protection 
- Command checklist is automatically added to a `task.json` file and exected in order. This  avoids errors when setting up the repo.  
Codesandbox also has a [Template for create-T3-app](https://codesandbox.io/p/sandbox/sharp-euclid-6k4sdn) running on Cloud sandboxes powered by micro VMs
https://codesandbox.io/p/sandbox/sharp-euclid-6k4sdn
- [ x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ x] The PR title follows the convention …

docs: Add option to contribute via Codesandbox

---

.changeset/hungry-cups-worry.md
www/src/components/navigation/navbar.astro

Closes #1228
---
_Added the lang code var to the array of links used in the navbar_
---
https://user-images.githubusercontent.com/17475188/220187279-41485a02-5db9-424b-99b4-ca3e425cd130.mp4
💯

fix: Added dynamic lang code to navigation links

---

.changeset/poor-grapes-think.md
cli/src/index.ts

Closes #1251
---
Moved the renaming of the `_eslint.cjs` file to before the git initialization to ensure the file is included by default.
---
Repo with what will be output and included in git by default. 
Options: Typescript, no packages, yes initialize git, yes npm install, default import alias.
ran `git commit` without any other changes made
https://github.com/ggrochow/create-t3-example
💯

fix: ensure .eslint.cjs is included in git

---

.changeset/great-buckets-relate.md
cli/src/cli/index.ts
cli/src/utils/validateImportAlias.ts
cli/src/utils/validatePathAlias.ts

---
- Add validation for import aliases
---
💯

feat: Add validation for import aliases

---

.changeset/nice-bugs-tickle.md
cli/template/base/_eslintrc.cjs

---
Reason for this change is that currently templates that don't do anything with args in createContext (ie any without next-auth) throw an eslint warning. Also using `_` as "i'm not using this" is a common enough pattern that I think it's worth allowing by default.
see: https://discord.com/channels/966627436387266600/1081204127327059998
💯

feat: ignore vars that start with `_` for eslint no-unused-vars ignore

---

.changeset/short-pugs-breathe.md
cli/template/base/next.config.mjs

Closes #1276
---
_Removed unnecessary comment in next.config_
---
💯

fix: remove //@ts-check comment

---

.changeset/eighty-masks-invite.md
cli/package.json
cli/template/extras/src/server/api/trpc/base.ts
cli/template/extras/src/server/api/trpc/with-auth-prisma.ts
cli/template/extras/src/server/api/trpc/with-auth.ts
cli/template/extras/src/server/api/trpc/with-prisma.ts
pnpm-lock.yaml
www/src/pages/en/usage/trpc.md

feat: add errorformatter

---

.changeset/fresh-cars-tease.md
cli/template/base/_eslintrc.cjs

---
I created a t3-app in an existing monorepo and I expect eslint to use the config file that is in the project and not in the turborepo root. The current `.eslintrc.cjs` always searches for the `tsconfig.json` in the root of the project. I resolved the path to do a relative seach, which is what most people expect if there lies a `tsconfig.json` next to the `eslintrc.cjs`.
💯

fix: search for tsconfig relative to eslintrc

---

www/src/components/landingPage/tweets/tweets.astro
www/src/pages/index.astro

Turns out I unintentionally borrowed copy from Turbo, so I updated that. Also saw the embedded tweets were super out of date so I removed the widget for now

docs: update tweets copy, remove for now

---

.changeset/smart-cherries-try.md
cli/src/cli/index.ts

Closes #1281 
---
Replaced the Git Bash check if a check for Mintty. Git Bash works perfectly fine when using another terminal. Mintty is the issue here and it causes lots of issues with other CLI programs. 
Not too sure if we want two messages here, I think having a notice specific to Git Bash is needed as it is mainly Git Bash users who are having this issue (Since Git Bash uses Mintty by default). 
---
WSL VSC (Should not be affected by the change)
Git Bash + Mintty
Git Bash + Windows Terminal
💯

feat: Replace Git Bash check with Mintty check

---

www/src/components/docs/companyList.tsx

EcoToken is currently using the T3 stack with create-t3-turbo for development and production. I am looking to add it to the company list. You can find the source code here: https://github.com/ecoWarriors/web-ecotoken
---
EcoToken has been added to the company list on the docs website. A name, link name, and link has been provided appropriately.
---
💯

docs: adding ecotoken to the company list

---

.changeset/gold-toes-compete.md
cli/src/installers/dependencyVersionMap.ts

Closes https://github.com/t3-oss/create-t3-app/issues/1328
---
- pins next-auth to 4.20.1
- ive also subscribed to https://github.com/nextauthjs/next-auth/issues/7132 so we can hopefully undo this asap
---
💯

fix: temporarily pin next-auth version

---

www/src/components/docs/openSourceAppList.tsx

Prisma editor is a powerful tool to visualize and edit Prisma Schema. You can easily create, modify and maintain complex database structures and be sure that your databases are organized and consistent.
With Prisma Editor, you can take advantage of a variety of incredible features, including real-time visualization, a user-friendly interface, SQL generation, and even the ability to edit your schema directly from the graph. But that's not all! We have also integrated the power of OpenAI's natural language processing API, which enables you to generate boilerplate schema code using natural language prompts.
---
---
💯

docs: Add Prisma Editor

---

.changeset/purple-frogs-stare.md
cli/template/base/src/env.mjs
cli/template/extras/src/env/with-auth-prisma.mjs
cli/template/extras/src/env/with-auth.mjs
cli/template/extras/src/env/with-prisma.mjs

Closes #1369
---
Enforce `NEXT_PUBLIC_` env key on client, using other non-`NEXT_PUBLIC_` key on client will give you a type error.
---
💯

feat: Enforce `NEXT_PUBLIC_` env key on client with TS

---

.github/workflows/lighthouse.yml

Update lighthouse action to the latest to *hopefully* resolve the error when generating lighthouse audit for docs.
---
Updated lighthouse-ci-action to v9.
---
💯

feat: Update lighthouse-ci-action to v9

---

cli/template/extras/prisma/schema/with-auth.prisma

Reading https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string string seems to map to Text already in postgresql, so I think this part of the comment can be removed.
---
Remove mention of postgresql's need for `@db.Text`  in the Prisma schema

fix: clarify comments regarding prisma use of postgresql

---

.github/workflows/translations.yml

- add @vdeva for fr 
- add @uehaj and @t6adev for jp 
💯

chore: add translators

---

.changeset/pink-tigers-smoke.md
cli/template/base/package.json

see: 
- https://github.com/t3-oss/create-t3-app/issues/1399
- https://github.com/trpc/trpc/issues/4316
let's not count it as "resolved" until builds work on latest `next` version
💯

fix: temporarily pin `next` version to fix vercel build error

---

.changeset/clean-jobs-melt.md
cli/template/base/package.json

fix(deps): Update NextJS dependency to version ^13.4.1

---

www/src/components/navigation/OnThisPageLinks.tsx

---
- Fix small gap between main page header and on this page header links after 1023px media query break
---
Before fix:
After fix:
💯

fix: gap between navigation and on this page header on mobile view

---

.changeset/happy-squids-taste.md
cli/template/extras/src/server/auth/base.ts

Closes #1388 
---
When using NextAuth but not Prisma, the session user's id is now set to `token.sub` instead of `user.id` because `user` is undefined when not using database sessions.
```typescript
callbacks: {
session: ({ session, token }) => ({
...session,
user: {
...session.user,
id: token.sub,
},
}),
},
```
💯

fix: use token.sub instead of user.id when using auth and not prisma

---

www/src/components/docs/avatarList.astro
www/src/styles/accessibility.css

Closes partially  #881
---
Add outline focus outline on github contributors
---
🚀

docs: Focus styling on GitHub contributors

---

pnpm-lock.yaml
upgrade/package.json
upgrade/src/lib/utils.ts

Currently, we get a bunch of warnings from octokit because it's trying to use node-fetch@2.x which doesn't work well with next.
This PR migrates from @octokit/rest to @octokit/request@7.0.0-beta.2 which removes the use of node-fetch.
I'll make this PR a draft until they publish the stable release
---
---
💯

feat: Migrate from @octokit/rest to @octokit/request

---

.github/workflows/translations.yml

was causing japanese translation maintainers to not get pinged, see: https://github.com/t3-oss/create-t3-app/pull/1458#issuecomment-1570361842
💯

fix: incorrect language code for japanese translators github action

---

www/src/components/landingPage/stack/card.astro

---
- Remove extra blank line space in Next.js & tRPC cards
---
- Current
- After
- For reference, this is how it looked like before [PR1243](https://create-t3-app-git-fork-albbus-stack-patch-1-t3-oss.vercel.app/) was merged
💯

fix(www): remove extra line space in Tech Stack Cards of Landing Page

---

.changeset/healthy-toes-matter.md
cli/template/base/src/pages/index.tsx
cli/template/extras/src/pages/index/with-auth-trpc-tw.tsx
cli/template/extras/src/pages/index/with-auth-trpc.tsx
cli/template/extras/src/pages/index/with-trpc-tw.tsx
cli/template/extras/src/pages/index/with-trpc.tsx
cli/template/extras/src/pages/index/with-tw.tsx

Closes https://twitter.com/ccccjjjjeeee/status/1668694515484336145
---
Remove React.FC usage in templates, replacing with standard function syntax
Per https://twitter.com/ccccjjjjeeee/status/1668694515484336145
---
💯

chore: Replace React.FC and NextPage types with basic function syntax

---

.changeset/perfect-geckos-behave.md
cli/src/cli/index.ts
cli/src/utils/parseNameAndPath.ts
cli/src/utils/removeTrailingSlash.ts
cli/src/utils/validateAppName.ts

Closes #1460
---
_Ignore trailing slashes when prompting the app name_
---
💯

feat: remove possible trailing slash from appName prompt

---

.changeset/funny-spoons-unite.md
cli/src/cli/index.ts
cli/src/utils/isTTYError.ts

---
Adds IsTTYError class and checks for instanceof that, instead of assigning an `isTTYError` key to a normal error. Extending the Error class for one-time use feels like a good tradeoff for not needing ESLint ignores and not having to write `if (err instanceof Error && (err as any).isTTYError)`.
💯

feat: use custom error class for isTTYError

---

.changeset/late-starfishes-kiss.md
cli/src/helpers/logNextSteps.ts

---
Added a reminder to git commit after creating an application with the CLI
---
💯

feat: add reminder to commit after creating app

---

www/src/components/navigation/githubIcon.astro

Closes #1488 
---
added spacing between github icon and star bubble icon
---
| before | after | 
| --- | --- |
| ![image](https://github.com/t3-oss/create-t3-app/assets/74069208/0be4c22c-44fd-4a1b-8d2d-cf0114d794e6) | ![image](https://github.com/t3-oss/create-t3-app/assets/74069208/75b50c60-a729-4725-9164-bacb715bbf06) |
💯

fix: add spacing between github icon and star bubble icon

---

.gitattributes

fix: make linguist ignore mdx

---

.changeset/red-melons-fly.md
cli/template/base/_eslintrc.cjs

Closes #1520
---
Disables `@typescript-eslint/array-type` and `@typescript-eslint/consistent-type-definitions` in the template provided to users.
---
Normally I'd leave a `good first issue` to someone new, but I'd like to get this in asap.
💯

feat: reduced stylistic linting

---

cli/template/extras/src/server/db/drizzle-schema-auth.ts

Closes #1485 
- [| ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ |] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [| ] I performed a functional test on my final commit
---
in the nextauth drizzle template I changes varchar to text on some fields to prevent errors when authenticating
---

fix(nextauth-drizzle): changed varchar to text on drizzle nextauth to prevent auth errors

---

.changeset/few-bikes-collect.md
cli/src/installers/dependencyVersionMap.ts

---
* Bump Prisma from ^5.0.0 to ^5.1.1
* Notably, [Prisma v5.1.0](https://github.com/prisma/prisma/releases/tag/5.1.0) removes some redundant queries for PostgreSQL and CockroachDB 🎉 
* Bump patch versions of a couple other deps while in the area
---
n/a

chore(deps): upgrade Prisma to v5.1.1, bump patch versions of other dependencies

---

www/src/pages/en/usage/next-js.md

Closes #1539 
---
_Update next-js.md to add an example on how to use getServerSideProps anyway_
---
💯

docs: Update next-js.md to add an example on how to use getServerSideProps anyway

---

www/src/components/navigation/navbar.astro

Closes #1552
1. Removed `data-navbar` from navbar.
2. Added `data-home-link` to anchor tag wrapping the logo.
3. Updated selector that applies right-click listener accordingly.
---
Minor, website navbar, right-click redirects to `/branding` page only for logo anchor, not entire navbar.
No packages need a version bump, no changeset applicable, website change only.

fix(website): make right-click ➝ /branding only for logo, not entire navbar

---

cli/package.json
cli/tsup.config.ts

no need to ship type declarations or src files to users. the CLI already includes a lot of files as is

chore: ship less files to users with the cli

---

.changeset/soft-moose-care.md
cli/src/index.ts

Closes #1538 
---
- Add packageManager field in package.json at app creation. Based on the package manager used.
---
💯

feat: set packageManager on app creation

---

.changeset/hungry-cameras-melt.md
.github/workflows/e2e.yml
cli/template/extras/src/env/with-auth-db.mjs
cli/template/extras/src/env/with-db.mjs

The default example url is a valid url so t3-env wont crash the app, so your app just silently wont work. Adding a refine checking for the default case to prevent this and make sure the app crash before you've changed the URL

fix(drizzle): yell if default url isn't cahnged

---

.vscode/settings.json

Closes #1579
---
Language specific formatters defined in project's `settings.json` and enable Tailwind Intellisesne sugggestions.
💯

feat: improved VSCode first time setup experience

---

cli/README.md

Closes [none]
---
Corrected a minor typo in README.md for the number of different commands for scaffolding an app.
---
💯

docs: correct number of commands for scaffolding an app

---

.changeset/sour-cooks-design.md
cli/README.md
www/src/components/landingPage/ClipboardSelect.tsx
www/src/components/landingPage/banner.astro
www/src/pages/ar/installation.mdx
www/src/pages/en/installation.mdx
www/src/pages/es/installation.mdx
www/src/pages/fr/installation.mdx
www/src/pages/ja/installation.mdx
www/src/pages/no/installation.mdx
www/src/pages/pl/installation.mdx
www/src/pages/pt/installation.mdx
www/src/pages/ru/installation.mdx
www/src/pages/zh-hans/installation.mdx
www/tailwind.config.ts

Closes [#1609](https://github.com/t3-oss/create-t3-app/issues/1609)
---
Add dropdown for different package manager copy to clipboard options on homepage
---
🫡💖

feat: Add Dropdown for Installation Commands on Homepage

---

.changeset/config.json
.changeset/smooth-radios-sparkle.md
.github/workflows/ci.yml
CONTRIBUTING.md
cli/template/extras/src/app/layout/with-trpc-tw.tsx
cli/template/extras/src/app/layout/with-trpc.tsx
cli/template/extras/src/trpc/react.tsx
cli/template/extras/src/trpc/server.ts

We only really need to forward the header so that tRPC and other stuff can authenticate the user. There are some issues with certain headers that we run into when sending every single header along (I know `transfer-encoding` and `content-length` are two that doesn't like playing nice)
Closes #1640
Closes #1641

fix: only forward required cookie header

---

.changeset/smooth-buckets-search.md
cli/template/base/_eslintrc.cjs

fix: replace a `2` with `"error"` in eslint config

---

.changeset/nervous-seals-reflect.md
cli/prettier.config.mjs
cli/template/extras/config/_prettier.config.js
upgrade/prettier.config.js
www/prettier.config.mjs

---
Use the correct types for `prettier-plugin-tailwindcss`
---
💯

fix: Use the correct types for `prettier-plugin-tailwindcss`

---

.changeset/thick-comics-punch.md
cli/template/extras/src/env/with-auth-db.js
cli/template/extras/src/env/with-auth.js

Closes https://github.com/t3-oss/create-t3-app/issues/1677
---
---
💯

fix: typo in env.mjs

---

.changeset/old-jokes-drive.md
cli/package.json
cli/src/installers/dependencyVersionMap.ts
cli/template/extras/config/drizzle.config.ts
pnpm-lock.yaml

Closes https://github.com/t3-oss/create-t3-app/issues/1699
---
- update drizzle-kit to ^0.20.7
- change the connectionString key to `uri` because thats what it uses now
💯

feat: update drizzle-kit and change connectionString to uri

---

.changeset/tidy-panthers-mate.md
.vscode/settings.json
cli/template/extras/src/server/api/trpc-app/with-auth-db.ts
cli/template/extras/src/server/api/trpc-app/with-auth.ts
cli/template/extras/src/server/api/trpc-pages/with-auth-db.ts
cli/template/extras/src/server/api/trpc-pages/with-auth.ts
www/src/pages/ar/usage/next-auth.md
www/src/pages/en/usage/next-auth.mdx
www/src/pages/es/usage/next-auth.md
www/src/pages/fr/usage/next-auth.mdx
www/src/pages/ja/usage/next-auth.md
www/src/pages/no/usage/next-auth.md
www/src/pages/pl/usage/next-auth.md
www/src/pages/pt/usage/next-auth.md
www/src/pages/ru/usage/next-auth.md
www/src/pages/zh-hans/usage/next-auth.mdx

Quick search & replace.
---
- Drops all `.use(myFn)` in favor of `.use(() => ...`-style
- I don't know why I ever recommended `t.middleware` in favor of inlining, it's only ever useful if you wanna use `.unstable_pipe()` which is rare for most apps
- Related PR in tRPC: https://github.com/trpc/trpc/pull/5237
---
💯

chore: drop `t.middleware()`

---

.changeset/fair-colts-approve.md
cli/template/base/_eslintrc.cjs
cli/template/base/package.json

Closes https://github.com/t3-oss/create-t3-app/issues/1674
references:
next eslint docs for app router: https://nextjs.org/docs/pages/building-your-application/configuring/eslint
next eslint docs for pages router (important stuff is the same as app dir): https://nextjs.org/docs/app/building-your-application/configuring/eslint
💯

fix: update eslint setup for next 14.0.4

---

.changeset/chatty-monkeys-battle.md
cli/package.json
pnpm-lock.yaml

---
Remove unused @types/inquirer
---
💯

chore: remove unused @types/inquirer

---

www/src/components/docs/breadCrumbs.tsx
www/src/components/docs/pageContent.astro

Closes #1711
---
Move the margin and height to the `div` wrapping the `BreadCrumbs` component.
---
Before:
https://github.com/t3-oss/create-t3-app/assets/1545970/2d6976e3-def1-4529-a462-9a60da242706
After:
https://github.com/t3-oss/create-t3-app/assets/1545970/78fc8e51-0ab3-4c19-bd73-fe772a3acb93

fix(docs): reserve height for breadcrumbs on server render

---

www/src/pages/ar/usage/trpc.md
www/src/pages/en/usage/trpc.md
www/src/pages/fr/usage/trpc.md
www/src/pages/ja/usage/trpc.md
www/src/pages/ru/usage/trpc.md

fix: fix typos in documentation

---

.changeset/plenty-pears-drum.md
cli/src/cli/index.ts
cli/template/extras/src/server/auth-app/with-drizzle.ts
cli/template/extras/src/server/auth-pages/with-drizzle.ts
www/src/pages/og.ts

There's a few missuses of binary expresions that make them constant evaluations.
This PR fixes them.
---
Fix constant binary expressions.
---
💯

fix: missuse of binary expressions

---

www/src/pages/pl/usage/first-steps.md

docs: update polish translation first-steps.md

---

.changeset/dirty-birds-own.md
cli/src/cli/index.ts
www/src/pages/ar/usage/prisma.md
www/src/pages/en/usage/prisma.md
www/src/pages/fr/usage/prisma.md
www/src/pages/ja/usage/prisma.md
www/src/pages/no/usage/prisma.md
www/src/pages/pl/usage/prisma.md
www/src/pages/pt/usage/prisma.md
www/src/pages/zh-hans/usage/prisma.md

~Closes #<issue>~
---
Noticed in my last run of `npx create-t3-app` that “PlanetScale” incorrectly appears as “Planetscale” in the prompt (screenshot below). This PR fixes that instance and a few instances across documentation. 
Disclosure: I am a PlanetScale employee 😄
---
💯

fix: correct casing of “PlanetScale”

---

.changeset/nervous-oranges-deliver.md
cli/src/installers/envVars.ts

fix: generated comments in env file

---

.changeset/sixty-rats-drop.md
cli/template/extras/src/trpc/react.tsx

Closes #1771
The way queryClient is initialized has been changed based on the following discussion within the Tanstack Query community: [discussion](https://github.com/TanStack/query/issues/6116)

fix: stable query client

---

.changeset/eight-balloons-whisper.md
cli/src/helpers/selectBoilerplate.ts
cli/template/extras/src/pages/_app/with-auth-trpc-tw.tsx
cli/template/extras/src/pages/_app/with-auth-trpc.tsx
cli/template/extras/src/pages/_app/with-auth-tw.tsx
cli/template/extras/src/pages/_app/with-trpc-tw.tsx
cli/template/extras/src/pages/_app/with-trpc.tsx
cli/template/extras/src/pages/_app/with-tw.tsx

Closes #1743 
---
This PR adds the missing default font to the `pagesDir`. This change made creating separate files for tailwind and native CSS necessary with the related changes to the `selectBoilerplate.ts` file.
I tested all permutations to get every combination of tailwind, trpc and auth - works as expected!
(Thanks for this awesome project btw!)
---
💯

fix: missing default font in pagesDir

---

.changeset/soft-stingrays-hammer.md
cli/src/helpers/logNextSteps.ts

Closes #1776
---
Updates `./cli/src/helpers/logNextSteps.ts` to only show planetscale error if using the mySQL driver
---
Before:
After:
If you are using mySQL you get:
💯

fix: Don't show planetscale serverless warning if not installing driver

---

.changeset/proud-clocks-chew.md
cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

Closes #1789
---
Make scripts more portable across different nix systems by using `#!/usr/bin/env bash
` instead of `#!/bin/bash`
---
💯

refactor: use portable shebangs

---

cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

Closes #1796<issue>
---
`openssl rand -base64 12` can create passwords with `+` and `/` characters which when used as database urls have to be encoded.
In this modification, I introduced `tr '+/' '-_'` immediately after the `openssl rand -base64 12` command to replace `+` with `-` and `/` with `_`, making the generated base64 string URL-safe. This ensures that the `DB_PASSWORD` variable will contain a URL-safe string that can be used directly in database URLs without further encoding.
---
💯

fix: create url safe db passwords

---

.changeset/violet-plums-sparkle.md
cli/src/installers/eslint.ts

Closes #
---
- Apply drizzle-orm lint rules for specified keywords only (`db`)
---
💯

feat: apply drizzle lint rules to `db` keyword only

---

cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

---
- Improve the exit status and messages of the docker start-database scripts. It could fail and still say "Database container was successfully created".
- Run [shellcheck](https://www.shellcheck.net/) on the scripts and accepted the minor suggestions
<details>
```
$ shellcheck postgres.sh 
In postgres.sh line 15:
echo "Docker is not installed. Please install docker and try again.\nDocker install guide: https://docs.docker.com/engine/install/"
^-- SC2028 (info): echo may not expand escape sequences. Use printf.
In postgres.sh line 27:
source .env
^--^ SC1091 (info): Not following: .env was not specified as input (see shellcheck -x).
In postgres.sh line 29:
DB_PASSWORD=$(echo $DATABASE_URL | awk -F':' '{print $3}' | awk -F'@' '{print $1}')
^-----------^ SC2086 (info): Double quote to …
```

fix: improve start-databse scripts exit and messages

---

.changeset/beige-pets-yell.md
cli/src/helpers/logNextSteps.ts

fix: `start-database.sh` is marked optional

---

.changeset/great-hornets-remain.md
cli/template/extras/src/trpc/react.tsx

I believe the correct place for this is in trpc/react.tsx to expose it to the client
Discord Questions about this:
https://discord.com/channels/966627436387266600/988912020558602331/1231632715493802085
---
Exposes inferRouterInputs<AppRouter> & inferRouterOutputs<AppRouter> as RouterInputs & RouterOutputs to the client in the app router
---
💯

feat: expose trpc types to client for app router

---

.changeset/unlucky-poems-appear.md
cli/src/cli/index.ts

Reverts t3-oss/create-t3-app#1840

chore: stabilize app router and make it defautl

---

.changeset/tough-mice-drop.md
cli/template/base/_gitignore

fix: Added drizzle's db.sqlite location to .gitignore

---

.changeset/selfish-geese-camp.md
cli/src/installers/dbContainer.ts

Closes #1834
---
NOTE: I was messing with my forked repo and accidentally closed the original [pr](https://github.com/t3-oss/create-t3-app/pull/1857) because of a rebase of the main branch.
The dbContainer.ts file in cli/src/installers/dbContainer.ts was updated with a parseNameAndPath function when a projectName of "." was used. This was done with a ternary and destructuring to keep the type safety of the variable.
I had a few options.  
1. I could change the start-database.sh script to check for "." project names and change accordingly
2. I could change the file that was changing the start-database.sh file
I decided to go with the last route because it's a single source of truth and can be used for future implementations.
I followed the data flow of projectName and scopedProjectName …

fix: start-database.sh CONTAINER_NAME update with '.' project name (#1834)

---

cli/template/extras/src/server/db/schema-drizzle/base-postgres.ts
cli/template/extras/src/server/db/schema-drizzle/with-auth-postgres.ts

Closes #1863
---
added `withTimezone` option to all `timestamp()` calls in drizzle postgres. previously it was saving an incorrect timestamp, offset by -2h wrt UTC.
---

fix: incorrect timestamps in drizzle

---

.changeset/big-ghosts-draw.md
.github/workflows/e2e.yml
cli/src/cli/index.ts
www/src/pages/en/installation.mdx

Closes #1865
---
Inside [cli/src/cli/index.ts](https://github.com/t3-oss/create-t3-app/blob/main/cli/src/cli/index.ts)
Updated CI flags to include dbProvider with a default value of 'sqlite'
Updated default value of --dbProvider
Included an error check for the input of the --dbProvider value
Set cliResults.databaseProvider to a conditional value based on the user input
Included parser for both Drizzle and Prisma
Updated documentation to include CLI flags and examples
Feedback or advice is encouraged 💯 
💯

fix: updated --dbProvider CI flag to parse configured databases #1865

---

cli/template/extras/prisma/schema/with-auth.prisma

With the default config, trying to use `GithubProvider`, I found the error "Try signing in with a different account".
There was one missing field `refresh_token_expires_in` when `next-auth` tried to create a record `Account`. Should be fixed now.

fix(with-auth.prisma): add missing field refresh_token_expires_in

---

.changeset/dirty-snakes-rescue.md
cli/src/installers/eslint.ts

Closes #
---
Add `ctx.db` to the `drizzleObjectName` list for the drizzle eslint rules to be applied when using `ctx.db` in trpc routes.
Previously, it would only apply if you `import { db } from "@/db"`
---
💯

patch: apply drizzle eslint rules to `ctx.db`

---

.changeset/hot-chairs-fail.md
cli/src/installers/drizzle.ts
cli/src/installers/prisma.ts

---
- Add `db:generate` and `db:migrate` scripts
---
N/A
💯

feat: add `db:generate` and `db:migrate` scripts

---

upgrade/tailwind.config.ts
www/tailwind.config.ts

---
Update selector strategy in both `tailwind.config.ts` files.
---
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

fix: tailwind selector strategy changed in 3.4.1

---

www/src/components/docs/introductionTab.tsx
www/src/pages/en/introduction.mdx

Closes #1845 
---
updated the video tutorial for both pages and app router
---
💯

docs: added tabs to swtich app router and pages router tutorial

---

www/src/pages/en/deployment/docker.md

Closes #na
---
An issue is encountered when building the dockerfile and pnpm is the chosen engine - this is due to corepack checks.
Switched from using yarn for installing pnpm.
Issue is repeatable by running `docker build -t test . --pull` from the root of the repo.
Thanks for the awesome project!

docs: fix corepack issues with using yarn as default

---

www/src/pages/en/usage/trpc.md

All links in the trpc.md file that led to trpc.io were broken links - this updates them to the correct pages in the TRPC documentation.
Closes #1923
---
All links to trpc.io have been updated to the equivalent page in the new docs.
💯

docs: Fixed broken trpc.io links in TRPC docs page

---

.changeset/orange-meals-clean.md
cli/template/extras/src/server/db/schema-drizzle/base-mysql.ts
cli/template/extras/src/server/db/schema-drizzle/base-planetscale.ts
cli/template/extras/src/server/db/schema-drizzle/base-postgres.ts
cli/template/extras/src/server/db/schema-drizzle/base-sqlite.ts
cli/template/extras/src/server/db/schema-drizzle/with-auth-mysql.ts
cli/template/extras/src/server/db/schema-drizzle/with-auth-planetscale.ts
cli/template/extras/src/server/db/schema-drizzle/with-auth-postgres.ts
cli/template/extras/src/server/db/schema-drizzle/with-auth-sqlite.ts

fix: unify drizlze schema and fix sqlite timestamps

---

cli/src/installers/envVars.ts

Closes #1919 
---
Fixes for [#1919](https://github.com/t3-oss/create-t3-app/issues/1919)
Changes involves using scopedAppName instead of projectName on creation of env files
---
💯

fix: scopedAppName for env 

---

.changeset/orange-onions-argue.md
cli/template/extras/src/server/api/routers/post/with-auth-drizzle.ts
cli/template/extras/src/server/api/routers/post/with-auth-prisma.ts
cli/template/extras/src/server/api/routers/post/with-drizzle.ts
cli/template/extras/src/server/api/routers/post/with-prisma.ts

Closes #1943 
---
Handle tRPC getLatest route when there are no posts yet
---
💯

fix: closes #1943

---

.changeset/twenty-items-cry.md
www/src/pages/ar/usage/prisma.md
www/src/pages/es/usage/prisma.md
www/src/pages/fr/usage/prisma.md
www/src/pages/ja/usage/prisma.md
www/src/pages/no/usage/prisma.md
www/src/pages/pl/usage/prisma.md
www/src/pages/pt/usage/prisma.md
www/src/pages/ru/usage/prisma.md
www/src/pages/uk/usage/prisma.md
www/src/pages/zh-hans/usage/prisma.md

---
Updating the import of the `db` in `prisma/seed.ts` in the documentation.
---
💯

docs: update prisma seed

---

www/.astro/settings.json
www/src/pages/en/usage/trpc.md

Update the reference link of React Query Docs in t3 tRPC usage documentation.
closes #1923
---
Change the latest tRPC docs link
---
💯

docs:Update the link to the latest trpc Docs

---

cli/template/extras/src/server/api/routers/post/base.ts
cli/template/extras/src/server/api/routers/post/with-auth-drizzle.ts
cli/template/extras/src/server/api/routers/post/with-auth-prisma.ts
cli/template/extras/src/server/api/routers/post/with-auth.ts
cli/template/extras/src/server/api/routers/post/with-drizzle.ts
cli/template/extras/src/server/api/routers/post/with-prisma.ts
cli/template/extras/src/server/api/trpc-app/base.ts
cli/template/extras/src/server/api/trpc-app/with-auth-db.ts
cli/template/extras/src/server/api/trpc-app/with-auth.ts
cli/template/extras/src/server/api/trpc-app/with-db.ts
cli/template/extras/src/server/api/trpc-pages/base.ts
cli/template/extras/src/server/api/trpc-pages/with-auth-db.ts
cli/template/extras/src/server/api/trpc-pages/with-auth.ts
cli/template/extras/src/server/api/trpc-pages/with-db.ts

fix: async/await in `getLatest` procedure, reduce dev delay and add fuzz

---

www/.astro/settings.json
www/src/components/navigation/githubIcon.astro

---
The GitHub star count was not displaying correctly. Previously, the "githubStars" in "githubicon.astro" file variable was not being updated with the fetched star count, causing the display to remain at the fallback value of "23K."
Updated the code to correctly display GitHub star. The "githubStars" variable now correctly reflects the fetched star count instead of using a fixed fallback value, ensuring accurate formatting and display of large numbers.
---
💯

fix: github stars count

---

.changeset/violet-elephants-sit.md
cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

Closes #1974
---
_added an extra check in the initial steps of the start-database.sh script to check if the docker daemon is up and running to prevent the script from continuing with for example generating the password_
---
before:
```
❯ ./start-database.sh
Cannot connect to the Docker daemon at unix:///Users/paulvanderlei/.docker/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///Users/paulvanderlei/.docker/run/docker.sock. Is the docker daemon running?
You are using the default database password
Should we generate a random password for you? [y/N]:
```
after:
```
❯ ./start-database.sh
Docker deamon is not up and running. Please start docker and try again.
```
💯

fix: resolved database startup script not checking docker daemon status  @0pilatos0

---

.changeset/lucky-parents-invent.md
cli/template/extras/src/app/page/with-auth-trpc-tw.tsx
cli/template/extras/src/app/page/with-auth-trpc.tsx
cli/template/extras/src/server/api/routers/post/with-auth-drizzle.ts

Fixes #1961
Add condition to prefetch `getLatest` only if the user is authenticated.
Align all auth templates to use `protectedProcedure` for `getLatest` method.

fix: conditional prefetch for protectedProcedure in auth templates

---

cli/src/installers/dbContainer.ts

Closes #1928  
---
- Added sanitizeName function to enforce Docker naming conventions by sanitizing project names.
- Updated dbContainerInstaller to sanitize the parsed project name before writing to the script.
- Modified replacement logic in fs.writeFileSync to use the sanitized project name instead of the placeholder "project1."
---
💯

fix: Sanitize project name for WSL compatibility while running start-database.sh

---

www/src/pages/en/installation.mdx

---
Update the docs to include the "--appRouter" cli flag as an option.
---
Before:
After:
💯

docs: added --appRouter CLI flag to docs

---

.changeset/strange-sheep-argue.md
cli/src/installers/envVars.ts

Closes #2009
---
Added the import of crypto from 'node:crypto' to `envVars.ts`
---
💯

fix: crypto not defined in cli envVars.ts. t3-oss/create-t3-app#2009

---

.changeset/itchy-apricots-compare.md
cli/template/extras/src/server/api/trpc-app/with-auth-db.ts
cli/template/extras/src/server/api/trpc-app/with-auth.ts
cli/template/extras/src/server/api/trpc-pages/with-auth-db.ts
cli/template/extras/src/server/api/trpc-pages/with-auth.ts
www/src/pages/ar/usage/next-auth.md
www/src/pages/en/usage/next-auth-app-router.mdx
www/src/pages/en/usage/next-auth-pages.mdx
www/src/pages/es/usage/next-auth.md
www/src/pages/fr/usage/next-auth.mdx
www/src/pages/ja/usage/next-auth.md
www/src/pages/no/usage/next-auth.md
www/src/pages/pl/usage/next-auth.md
www/src/pages/pt/usage/next-auth.md
www/src/pages/ru/usage/next-auth.md
www/src/pages/uk/usage/next-auth.mdx
www/src/pages/zh-hans/usage/next-auth.mdx

Closes #2043
---
fix: simplify session user check, in protected procedures #2044
---
💯

fix: simplify session user check in protected procedures

---

www/src/pages/en/folder-structure-app.mdx
www/src/pages/en/folder-structure-pages.mdx

---
There were incorrect links to Prisma docs in Drizzle sections in both folder structure pages.
Correct Drizzle docs links were added when applicable, and incorrect Prisma links were removed.
---

docs: fix drizzle links in folder structure

---

www/src/pages/en/usage/drizzle.mdx

Closes #1613
- [ x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] I performed a functional test on my final commit
---
Added documentation for the Drizzle page. Included relevant code snippets and documentation links. Replicated the overall structure of the Prisma section for consistency .
---
💯

docs: add documentation for drizzle

---

cli/template/base/tsconfig.json

---
This PR enables the `verbatimModuleSyntax` option in the `tsconfig.json` to automatically prefix `type` to type imports. Since we have the `[@typescript-eslint/consistent-type-imports]` rule enabled, it was becoming tedious to manually add the type keyword for every type import.
💯

feat(tsconfig): enable verbatimModuleSyntax for type imports

---

.changeset/sour-pots-juggle.md
.github/workflows/pr-labeler.yml
cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

Closes #2060 
---
fix start-database.sh to not create an `.env-e` file, which is not gitignored, thus preventing exposure of auth secret, fixes #2060
---
before:
after:
💯

fix: prevent start-database.sh from creating .env-e, fixes #2060

---

.changeset/tricky-jars-flash.md
cli/template/extras/start-database/mysql.sh
cli/template/extras/start-database/postgres.sh

- [ x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] I performed a functional test on my final commit
---
Update start-database templates to support Docker Desktop or Podman Desktop
---

feat: Update start-database templates to support Docker Desktop or Podman Desktop

---

.changeset/neat-hounds-develop.md
cli/src/helpers/format.ts
cli/src/index.ts

Closes #2080 
---
fixes an issue with npm and pnpm when installing.
* npm: all cases
* pnpm: when not allowing `pnpm install` to be run
---
💯

fix: format breaks npm and edge case for pnpm #2080

---

.changeset/fresh-singers-hug.md
cli/template/base/tsconfig.json

Closes #2094 
---
Include new eslint.config.js file in tsconfig.json instead of .eslintrc.cjs
---
💯

fix: replace .eslintrc.cjs with eslint.config.js in tsconfig.json include array

---

.changeset/strong-poems-sing.md
cli/src/helpers/format.ts

---
Changed log that said that eslint was ran when prettier was ran.

fix: Fix log saying eslint is ran when prettier is ran
