- src/index.ts
implements #34
has been tested.
> feat: use project name in package.json

- CONTRIBUTING.md
Many OSS project have a `CONTRIBUTING.md` file or similar which helps ease newcomers into contributing to the project. Since I didn't see one, I thought I'd take a crack at a (simple) version of this document. Feel free to extend or propose changes!
> feat: add CONTRIBUTING.md for newcomers

- README.md
> reduce logo size in readme

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/utils/renderTitle.ts
Closes #60
Looked into animations but they seem quite buggy and doesn't work well with the interactiveness of the CLI. There are some GIFs in the issue showcasing the different results.
Feel free to keep coming with suggestions, this one is inspired by the [pomandres vscode theme](https://github.com/drcmda/poimandres-theme). This is how it currently looks: 
I haven't added any changelogs or package versioning so let me know when you're merging and I'll make sure to sync that.
> feat: pretty print welcome title

- README.md
I think pnpx got replaced by pnpm dlx since version 7?
> replaced pnpx with pnpm dlx in README

- template/addons/tailwind/tailwind.config.js
Tailwind 3.1 introduced [first party types](https://tailwindcss.com/blog/tailwindcss-v3-1#first-party-type-script-types)
> Add tailwind types annotation

- README.md
If y'all don't want this here totally fine
> Add link to Theo's youtube video

- template/page-studs/index/with-auth-trpc-tw.tsx
- template/page-studs/index/with-trpc-tw.tsx
- template/page-studs/index/with-tw.tsx
See #91 & #93. I'm better at Tailwind than Github.
> misc. tailwind fixes

- README.md
The readme didn't specify that the dependencies are **OPTIONAL** so I updated it a bit.
Moved "usage" to the top and split so the "copy" button works as expected
Going to write a more formal "T3 Axioms" later
> Format the readme a bit

- README.md
Sorry I keep seeing small things I promise I'll close vscode now
> More light readme cleanup

- README.md
Right now the badges are pointing to the svg file. When you click them it redirects you to that. I fixed it by adding the npm url and the contribution guide url
> docs: update readme with links to npm and the contribution guide

- .prettierrc
> add tabWidth

- template/page-studs/index/with-auth-trpc-tw.tsx
- template/page-studs/index/with-trpc-tw.tsx
- template/page-studs/index/with-tw.tsx
When added UI changes to templates h1 tags was removed  😆
see https://github.com/t3-oss/create-t3-app/pull/115
> fix(templates): h1 restored

- README.md
Got some feedback from an old colleague that it was "unclear" what create-t3-app was from the start. Hopeful this helps
> fix: More clarity in readme

- src/cli/index.ts
- src/consts.ts
- src/index.ts
- src/utils/renderTitle.ts
- template/base/package.json
There were some commits left behind.
> update main from dev

- template/base/src/pages/_app.tsx
- template/page-studs/_app/with-auth.tsx
Fix an issue in the _app.tsx where it would give this error. This is because the curly braces aren't needed, it is already getting it from "next/app", so you wouldn't need the curly braces anymore.
Before changes:
After changes:
> Follow patterns of the project.

- .github/pull_request_template.md
Example:
---
_[Short summary/description of story/feature/bugfix]_
---
💯
> docs: add pull requests template

- .github/workflows/PR-CI.yml
- package.json
- src/helpers/installPackages.ts
---
Installing deps globally once for all jobs, caching, and actions updates.
- Significantly faster CI per Pull Request or Push.
- Currently using minimal caching, can add caching later that actually skips steps when nothing has changed. 
- Updated all the GitHub Actions to their latest versions, has performance, security and other benefits.
- BIG change is that moved "jobs" into "steps" which allows the usage of installed deps, pnpm, and node to be reused between commands rather than rebuilding the environment for each check.
- Very different jobs can be moved into their own Workflow or Job, similar tasks should all be in the same job i.e. "PR Checks"
---
"Fork Testing" 
💯
> chore: ci improvements

- CONTRIBUTING.md
- README.md
---
Added some information throughout that was missing, reformatted some of the layouts that were a bit wonky, and streamlined the language for clarity and readability.
---
💯
> docs: README Revamp

- .lintstagedrc
- package.json
---
To be consistent since we are also using other files for other config (prettier, eslint,...)
Related issue: #170
> chore: move lintstaged config into file

- README.md
---
Added usage or beta and next versions under CLI Docs in the README.
---
> docs(readme): add usage for beta and next version

- template/addons/next-auth/api-handler-prisma.ts
- template/addons/next-auth/api-handler.ts
> chore: remove credentials provider

- src/utils/getUserPkgManager.ts
---
remove `getUserPkgManager` unnecessary blocks
---
💯
> refactor(utils): remove unnecessary blocks

- template/addons/next-auth/next-auth.d.ts
---
fixes #254 Fixes missing type in `next-auth` module augmentation.
---
> fix: missing next-auth types

- README.md
- template/base/README.md
---
- Added deployment strategy to the README
- Also fixed the vercel affiliate link in the create-t3-app README
---
> feat: add deployment strategy to generated README

- template/addons/next-auth/next-auth.d.ts
applying https://github.com/t3-oss/create-t3-app/pull/282 to next
> feat: make session.user.id nullable (next)

- template/base/src/env/client.mjs
- template/base/src/env/server.mjs
---
This is a POC fix to demonstrate the problem in issue #263
> fix: typeerror in env validation

- src/utils/parseNameAndPath.ts
> chore: redo #303 on next

- README.md
> chore: upload T3 logo to github

- .changeset/nervous-chefs-tie.md
- .eslintrc
- template/addons/prisma/client.ts
- template/base/.eslintrc.json
- template/base/package.json
Closes #272
---
Adds a very minimal, unopinionated lint config for Typescript
---
💯
> feat: add base tslint

- CONTRIBUTING.md
- cli/template/base/README.md
- package.json
- turbo.json
- www/docs/faq.md
- www/docs/installation.md
- www/docs/t3-axioms.md
- www/docs/t3-collection.md
- www/docusaurus.config.js
- www/sidebars.js
---
- Add FAQ page in docs
- Add additional usage in installation
- Add tutorials in generated readme
- Add me3 in t3 collection
- Change getting started page to t3 axioms
- Update contributing guide
- Add script to run the docs site
---
> docs: write some docs

- cli/template/addons/trpc/auth-context.ts
- cli/template/addons/trpc/auth-prisma-context.ts
- cli/template/addons/trpc/base-context.ts
- cli/template/addons/trpc/prisma-context.ts
> feat: make context independent of req/res

- cli/template/addons/trpc/auth-context.ts
> fix: typo in auth-context.ts

- cli/template/addons/trpc/base-context.ts
- cli/template/addons/trpc/prisma-context.ts
---
Applies https://github.com/t3-oss/create-t3-app/pull/334 to next
💯
> fix: build fails on trpc, trpc+prisma (next)

- cli/package.json
- cli/src/utils/addPackageDependency.ts
- pnpm-lock.yaml
see: https://github.com/t3-oss/create-t3-app/pull/357#issuecomment-1229144860
---
```json
{
"name": "my-t3-app",
"version": "0.1.0",
"private": true,
"scripts": {
"build": "next build",
"dev": "next dev",
"postinstall": "prisma generate",
"lint": "next lint",
"start": "next start"
},
"dependencies": {
"@next-auth/prisma-adapter": "^1.0.4",
"@prisma/client": "^4.1.0",
"@tanstack/react-query": "^4.2.1",
"@trpc/client": "10.0.0-alpha.48",
"@trpc/next": "10.0.0-alpha.48",
"@trpc/react": "10.0.0-alpha.48",
"@trpc/server": "10.0.0-alpha.48",
"next": "12.2.5",
"next-auth": "^4.10.2",
"react": "18.2.0",
"react-dom": "18.2.0",
"superjson": "^1.9.1",
"zod": "^3.18.0"
},
"devDependencies": {
"@types/node": "18.0.0",
"@types/react": "18.0.14",
"@types/react-dom": "18.0.5", …
```
> chore(addPackageDependency): sort `pkgJson`

- cli/template/base/README.md
- www/src/pages/en/deployment/docker.md
---
- now using `docker compose` instead of `docker-compose` ([reference](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command))
- fixed the docker compose describtion I messed up with my suggestion in #333
- updated to the latest docker compose file version (3.9)
- added a `Further reading` section with useful docker docs references
> docs: improve docker instuctions

- cli/template/page-studs/index/with-auth-trpc-tw.tsx
- cli/template/page-studs/index/with-auth-trpc.tsx
- cli/template/page-studs/index/with-trpc-tw.tsx
- cli/template/page-studs/index/with-tw.tsx
---
Move some stuff around so that it matches no matter what template is chosen.
Every template now follows:
- Home
- export Home
- AuthShowcase (if selected)
- TechnologyCardProps
- TechnologyCard
---
💯
> refactor: move stuff around

- .github/workflows/ci.yml
- cli/src/cli/index.ts
---
Adds matrix e2e tests (test building every combination)
---
💯
> chore(ci): matrix e2e test

- cli/src/cli/index.ts
> chore(ci): fix typo in index.ts

- .changeset/clean-snails-teach.md
- cli/template/base/src/env/client.mjs
~~- [ ] I performed a functional test on my final commit~~
---
- Extending the warning message for invalid client environment variables by including the reason
---
💯
> refactor: easier to understand client env warning

- cli/src/installers/index.ts
- cli/template/addons/trpc/auth-server-utils.ts
- cli/template/addons/trpc/server-utils.ts
- cli/template/page-studs/index/with-auth-trpc-tw.tsx
- cli/template/page-studs/index/with-auth-trpc.tsx
- cli/template/page-studs/index/with-trpc-tw.tsx
- cli/template/page-studs/index/with-trpc.tsx
---
Updates tRPC to Alpha 69
---
💯
> chore: update to alpha 69

- cli/src/installers/index.ts
- cli/template/addons/trpc/utils.ts
> chore: proxy-alpha.70

- .changeset/strong-spoons-obey.md
- cli/template/page-studs/index/with-auth-trpc-tw.tsx
Closes #418
---
Remove unnecessary singlequote in tailwind classname.
---
|before|after|
|-|-|
|![ScreenCapture 2022-09-10 23 48 35](https://user-images.githubusercontent.com/80559385/189488653-ed486e5e-a9b3-4e2a-b50a-c1cac30ec46a.png)|![ScreenCapture 2022-09-10 23 48 23](https://user-images.githubusercontent.com/80559385/189488651-7265887c-6b89-4c4f-b84e-eb77ae5c43cc.png)|
💯
> fix: remove unnecessary singlequote in tailwind classname

- www/src/pages/en/faq.md
---
- Added a new header for the tutorials with sub-headers for articles and videos
- Added [Migrating your T3 App into a Turborepo](https://www.jumr.dev/blog/t3-turbo) article
- Added [The T3 Stack - How We Built It](https://www.youtube.com/watch?v=H-FXwnEjSsI) and [An overview of the create T3 App](https://www.youtube.com/watch?v=VJH8dsPtbeU) videos
---
💯
> docs: Flesh out learning resource section of FAQ

- .changeset/quick-rabbits-breathe.md
- cli/template/base/.env-example
Closes #424 
---
Directs developer to add schema from .env to /env/schema.mjs for zod validation. See #424
---
💯
> feat: direct developer to add schema from .env to schema.mjs for zod validation

- .prettierrc
---
Without this, running prettier from CLI seems to ignore .astro files
💯
> feat: add prettier-plugin-astro to .prettierrc

- .github/workflows/lighthouse.yml
> fix: get preview url

- cli/template/addons/trpc/utils.ts
(nothing to test)
---
It seems like the comment was left untouched after additional helper types were added
💯
> docs: clear helper types description

- CONTRIBUTING.md
Closes #442 
- [] I performed a functional test on my final commit
---
Reworded current contribution instructions, and added terminal commands. Should make it easier for first time contributors and newer developers with less git experience.
---
💯
> feat(docs): increased clarity for how to contribute

- www/src/components/blog/pageContent.astro
- www/src/components/navigation/SidebarToggle.tsx
- www/src/components/navigation/moreMenu.astro
- www/src/layouts/blog.astro
- www/src/styles/global.css
---
chore(ui): redistributed columns on main grid
fix(ui): fixed glitches from index.css removal
fix(ui): fixed sidebar toggle
---
💯
> fix: css fixes and brought back the SidebarToggle functionality

- www/src/components/navigation/Search.tsx
- www/src/components/navigation/TableOfContents.tsx
- www/src/components/navigation/ThemeToggleButton.tsx
- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/moreMenu.astro
- www/src/components/navigation/navbar.astro
- www/src/components/navigation/rightSidebar.astro
- www/src/layouts/blog.astro
- www/src/layouts/landingPage.astro
- www/src/pages/en/usage/env-variables.md
- www/src/pages/en/usage/prisma.md
- www/src/styles/global.css
> fix: some ui

- .changeset/tall-pans-dream.md
- cli/src/helpers/logNextSteps.ts
- cli/src/helpers/scaffoldProject.ts
---
same as this but on the next branch https://github.com/t3-oss/create-t3-app/pull/446
💯
> feat: better cli text when scaffolding in '.' (next)

- .lintstagedrc
> fix: add astro formatting to .lintstagedrc (#463)

- cli/template/base/README.md
- www/src/components/footer/footer.astro
- www/src/config.ts
- www/src/pages/en/deployment/docker.md
- www/src/pages/en/deployment/vercel.md
- www/src/pages/en/faq.md
- www/src/pages/en/installation.md
- www/src/pages/en/t3-collection.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/next-js.md
- www/src/pages/en/usage/tailwind.md
- www/src/pages/en/usage/typescript.md
- www/src/pages/en/why.md
---
- Minor tweaks to the docs, made changes to the semantics and grammar
- Added NextAuth.js section in the why page
- Added Tailwind usage section
- Made the footer more minimal
- Added useful resources to a bunch of pages
---
> feat(docs): minor tweaks and improvements

- .changeset/plenty-owls-doubt.md
- www/src/pages/en/t3-collection.md
---
Added link to personal portfolio in t3-collection page
---
💯
> docs: added portfolio to OSS links

- cli/src/installers/index.ts
---
bumps trpc v10 to beta
---
💯
> feat: v10 beta

- www/src/components/footer/footer.astro
Closes #490 
---
Removed `w-screen` class from the `<footer>` element as well as redundant `clsx` call and import.
---
> fix(docs): footer overflow

- www/src/components/footer/footer.astro
- www/src/components/landingPage/about.astro
- www/src/components/landingPage/banner.astro
- www/src/components/landingPage/cli.tsx
- www/src/components/landingPage/community/community.astro
- www/src/components/landingPage/pageSection.astro
- www/src/components/landingPage/stack/card.astro
- www/src/components/landingPage/stack/stack.astro
- www/src/components/landingPage/tweets/tweetSlider.tsx
- www/src/components/landingPage/tweets/tweets.astro
- www/src/components/navigation/Search.tsx
- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/navbar.astro
- www/src/styles/swiper.css
> chore(docs): some improvements to landing

- www/src/components/landingPage/banner.astro
> fix: grammatical error on landing page banner

- .changeset/eighty-coats-tie.md
- cli/src/installers/nextAuth.ts
- cli/src/utils/runPkgManagerInstall.ts
Closes https://github.com/t3-oss/create-t3-app/issues/504
---
hard codes next-auth version to 4.10
💯
> fix: temp fix for next-auth peer deps (main)

- www/src/pages/en/usage/tailwind.md
---
- Added information about formatters and conditionally applying classes
---
> feat(docs): add more tailwind usage

- .changeset/fast-carrots-joke.md
- cli/src/installers/tailwind.ts
- cli/template/addons/tailwind/prettier.config.cjs
- cli/template/base/package.json
Closes #516 
---
Add prettier and prettier-plugin-tailwindcss
---
> feat(prettier): Add prettier and prettier-plugin-tailwindcss to cli output

- www/src/pages/en/usage/tailwind.md
---
Now we have tailwind css prettier plugin
---
> docs(tailwind): change docs for formatting tw classes

- www/src/components/navigation/leftSidebar.astro
- www/src/layouts/docs.astro
- www/src/styles/global.css
Closes https://github.com/t3-oss/create-t3-app/issues/525
---
- fixes the behavior of the docs table of contents scrollbar
- big prettier diff on `globals.css` but the only actual change in that file is in .t3-scrollbar
💯
> fix: docs scrollbar behavior

- cli/src/installers/index.ts
> chore: bump to beta.11

- pnpm-lock.yaml
- www/package.json
- www/tailwind.config.cjs
---
JetBrains Mono for codeblocks. Looks much better imo.
---
> feat: use jetbrains mono for code

- www/src/components/accessibility/jumpToContent.astro
- www/src/components/navigation/navbar.astro
- www/src/layouts/docs.astro
- www/src/layouts/landingPage.astro
- www/src/pages/themeTest.astro
- www/src/styles/accessibility.css
---
- jump to content button (only visible when focussed)
- prefers-reduced-motion media query -> disables smooth scrolling, transitions and animations
> feat(website): add basic accessibility features

- www/src/components/navigation/tableOfContents.astro
Closes #538 
---
Fix a TypeError occurring in `tableOfContents.astro`
---
💯
> fix: docs TypeError

- .github/labeler.yml
- www/src/pages/index.astro
Closes https://github.com/t3-oss/create-t3-app/issues/547
---
Change glob format based on: https://github.com/actions/labeler#basic-examples
I believe this will work, but can't actually test it in this repo specifically without merging.
💯
> fix: labeler CI action misses some PRs

- www/src/pages/en/faq.md
Closes #
Added brief paragraph letting the user the recommended way to "learn" the T3 Stack. Since this is a question that comes up constantly on Discord and wasn't documented here, I figured I would add the response to the docs and also link to a Theo video where he says the recommendation as well.
---
---
💯
> docs: added recommendation in FAQ

- README.md
In conjunction with #575 
adds a deprecation warning to the main branch's readme
> chore: add warning to main readme

- .changeset/chilly-seals-jump.md
- cli/src/installers/index.ts
- cli/template/base/package.json
> fix: version bumps on trpc and ts

- www/src/pages/en/usage/env-variables.md
---
Add information about `.env-example` to docs
💯
> feat: add .env-example info to docs

- cli/template/page-studs/_app/with-auth.tsx
---
Man I thought I had fixed this but somehow this semicolon came again here.
---
> fix(template): remove semicolon in _app of with-auth template

- .changeset/silly-ways-pay.md
- cli/template/addons/tailwind/prettier.config.cjs
---
prettier config is now typed and tailwind plugin doesn't complain
---
> feat(template): add prettier.Config type to prettier config and resolve plugin import

- www/src/components/landingPage/cli.tsx
---
- long lines now break on small screens instead of overflowing outside of the container
- the final "y" turns into "Yes" at the correct time
- (not resolved in this pr: weird spacing on some browsers)
---
💯
> feat: cli demo improvements

- .changeset/four-files-end.md
- cli/src/helpers/installDependencies.ts
- cli/src/helpers/scaffoldProject.ts
---
Make all success text green
---
(never mind the git bug, this is fixed in a different pr)
💯
> feat: consistent text color in terminal

- cli/template/base/next.config.mjs
- www/src/pages/en/faq.md
---
Seen some people struggling to implement i18n for a T3 App so made a reference for someone on Discord the other day. Thought it might be useful for others too? Fine to move it to the [T3-Collection](https://beta.create.t3.gg/en/t3-collection) too
---
💯
> docs: add i18n reference

- www/src/pages/en/faq.md
- www/src/pages/en/installation.md
> docs: add experimental CLI usage

- pnpm-lock.yaml
- www/package.json
- www/src/pages/en/usage/prisma.md
- www/src/pages/en/usage/trpc.md
---
Adds instructions on seeding (#617) and explain tRPC file structure.
https://create-t3-app-git-julius-docs-improvements-t3-oss.vercel.app/en/usage/trpc
---
💯
> docs: improvements on prisma and trpc

- README.md
- cli/template/base/README.md
Maintaining 2 (3) READMEs + the documentation will be difficult and quickly go out of sync. Moving some stuff from the READMEs to the respective documentation
> docs: move stuff from readme to docs

- cli/template/page-studs/_app/with-auth.tsx
---
Added a comment to keep consistency between the 3 page studs.
💯
> chore: add comment for consistency among studs.

- .changeset/dry-eagles-travel.md
- www/src/layouts/docs.astro
- www/src/styles/global.css
---
Headings inside the docs layout are now links, and upon click will copy to the clickboard.
---
💯
> feat: headings are now links and can be copied upon click

- .gitignore
- pnpm-lock.yaml
- www/.env.example
- www/.gitignore
- www/astro.config.mjs
- www/package.json
- www/src/components/landingPage/tweets/tweets.astro
- www/src/pages/en/t3-collection.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/prisma.md
- www/src/pages/en/usage/trpc.md
- www/src/pages/en/usage/typescript.md
- www/src/styles/global.css
- www/tailwind.config.cjs
> docs: add code-titles and write some docs

- cli/template/base/next.config.mjs
- cli/template/base/tsconfig.json
- www/src/pages/en/deployment/docker.md
Related to #603 
---
- Use top-level await in the `next.config.mjs`.
- Change tsconfig target to es2017.
💯
> feat: use top-level await to import server envs

- .changeset/nice-trees-pay.md
- cli/src/installers/index.ts
- cli/src/installers/trpc.ts
> chore: bump dependencies

- www/src/components/docs/avatarList.astro
- www/src/components/navigation/Search.tsx
- www/src/components/navigation/githubIcon.astro
- www/src/components/navigation/navbar.astro
- www/src/components/navigation/themeToggleButton.astro
- www/src/utils/fetchGithub.ts
> docs: iconify GitHub link

- www/src/pages/en/introduction.md
---
This PR corrects the NextAuth.js link (originally pointed to prisma.io).
---
> docs: fix nextauth.js link

- www/src/pages/en/introduction.md
Reverts t3-oss/create-t3-app#651
> Revert "docs: fix nextauth.js link"

- www/src/components/navigation/githubIcon.astro
> fix: clsx import and cache github data

- www/src/pages/en/introduction.md
---
This PR corrects the NextAuth.js link (originally pointed to `prisma.io`) & TailwindCSS link (originally pointed to `https://beta.create.t3.gg/en/(https:/tailwindcss.com/)`
_Redoing this PR since [last one](https://github.com/t3-oss/create-t3-app/pull/651) was made against `main`_
---
> docs: fix incorrect links

- www/src/pages/en/t3-collection.md
---
Fixed an incorrect/incomplete sentence.
---
N/A
💯
> docs(t3-collection): fix incomplete sentence

- www/src/pages/en/t3-collection.md
- [ X ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ X ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ X ] I performed a functional test on my final commit
---
- Fixed a deadlink 
---
N/A
💯
> docs: fixed dead link to t3.gg

- www/src/components/navigation/Search.tsx
- www/src/components/navigation/githubIcon.astro
- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/tableOfContents.astro
- www/src/components/navigation/themeToggleButton.astro
- www/src/layouts/docs.astro
- www/src/styles/global.css
---
Fixed small transition delay between the stars box and arrow on the right side (Had different transition functions)
Added the same hover effect on left menu items to right menu items
Added transitions to background + nav
---
[GH Icon](https://avrg.dev/1Ydp1.mp4)
[Right menu hover](https://avrg.dev/9t2dH.mp4)
💯
> fix: transitions on docs

- www/src/pages/en/usage/prisma.md
---
Link to `tsx` repo threw a 404 error. Updated with correct repo url.
---
💯
> docs: correct link to 'tsx' repo

- README.md
- www/src/config.ts
- www/src/pages/en/faq.md
- www/src/pages/en/installation.md
- www/src/pages/en/introduction.md
- www/src/pages/en/other-recs.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/next-js.md
- www/src/pages/en/usage/prisma.md
- www/src/pages/en/usage/tailwind.md
- www/src/pages/en/usage/trpc.md
- www/src/pages/en/usage/typescript.md
- www/src/pages/en/why.md
---
- try to explain some bits more clearly
- fix some grammar issues etc
- fix a few things that are factually incorrect, for example incorrect alt-text on alex's twitter image
Open to comments/revisions on all of this :)
💯
> docs: proofread docs and add 'other recommendations'

- www/src/components/landingPage/tweets/tweets.astro
---
- changed the twitter hashtag to `#create-t3-app` (open to discuss this of course, but a search for that gives about 20x more results than one for `#createt3app`, and it's our npm package name
- fixed the twitter link (it was redirecting to `beta.create.t3.gg/twitter.com`)
💯
> feat: docs twitter link and hashtag

- .changeset/popular-cars-laugh.md
- cli/src/installers/index.ts
- cli/template/addons/trpc/utils.ts
- cli/template/base/package.json
---
Version bumps on
- next 13.0.2
- trpc rc.4
- eslint ^8.26
- set free some @types packages that were looked
---
💯
> chore: version bumps

- www/src/components/landingPage/stack/stack.astro
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/next-js.md
- www/src/pages/en/usage/tailwind.md
> fix(doc): possible improvements and/or fixes (#686)

- www/src/pages/en/t3-collection.md
---
I added my project (myfaq.page) to the t3 collection.
> docs: added my project to the t3 collection

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> fix: Typo(s) in Issue Template(s) (#689)

- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/navbar.astro
- www/src/layouts/docs.astro
---
Fixed active page in sidebar (Not sure how but seems like I did somehow lol)
Fixed scrollbar in sidebar when on Firefox
Fixed nav header height increasing slightly on small device before breakpoint is hit
Fixed transition delay on mobile when nav menu is open
Fixed sidebar overflowing onto content at specific widths
---
Firefox scrollbar:
Nav height increase on small devices:
Content overflow:
Active page style
Mobile nav transition
[Broken](https://avrg.dev/Y85yK.mp4)
[Fixed](https://avrg.dev/3G32T.mp4)
💯
> fix(docs): fixed several style issues with docs

- www/src/components/landingPage/banner.astro
- www/src/components/landingPage/community/community.astro
- www/src/components/navigation/navbar.astro
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/prisma.md
---
- Fixed theme toggle button showing up on the landing page
- Consistent use of `GitHub` throughout the documentation. Replaced all `Github` with `GitHub`
- Fixed missing period in the Twitter community card on the landing page
---
Before: 
After: 
💯
> fix(docs): theme toggle showing up on landing page + minor changes

- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/navbar.astro
- www/src/layouts/docs.astro
---
- max width for navbar and docs
---
💯
> docs: max-width

- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/navbar.astro
- www/src/components/navigation/sidebarToggle.astro
- www/src/components/navigation/themeToggleButton.astro
- www/src/layouts/landingPage.astro
- www/src/pages/404.astro
- www/src/pages/en.astro
- www/vercel.json
Closes #698 
---
- Added redirect from `/en` to `/`
- Added basic custom 404 page with the landing page layout
---
💯
> feat: adds redirects and basic custom 404 page

- www/src/pages/en/why.md
---
- Fix missing periods + grammar stuff
---
💯
> docs: minor fixes

- www/src/components/navigation/leftSidebar.astro
Closes #709
- [✅] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [✅] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [✅ ] I performed a functional test on my final commit
---
- Fix the width on the left sidebar
---
OLD:
NEW:
💯
> fix: set full width to the left sidebar

- www/src/components/landingPage/stack/stack.astro
- www/src/pages/en/faq.md
---
- Fixed broken link in [FAQ](https://beta.create.t3.gg/en/faq)
- Typescript => TypeScript in [Landing Page](https://beta.create.t3.gg/)
---
💯
> docs: fix broken link + minor fixes

- www/tailwind.config.cjs
Closes #724
---
Changed "Inter" to "InterVariable" in tailwind config as it was already being used in the project.
---
💯
> feat: Use InterVariable in tailwind config

- .changeset/shaggy-vans-grab.md
- .github/workflows/e2e.yml
- cli/src/helpers/logNextSteps.ts
- cli/src/installers/envVars.ts
- cli/template/addons/env/auth-prisma-schema.mjs
- cli/template/addons/env/auth-schema.mjs
---
- Add `.min(1)` to Zod schema of `NEXTAUTH_SECRET`
- Add a comment to prevent keeping the secret empty in `.env`
- Warn the user to add the secret in cli next steps
---
- Add `.min(1)` to Zod schema of `NEXTAUTH_SECRET`
- Predefine `NEXTAUTH_SECRET=changeme` https://github.com/t3-oss/create-t3-app/pull/717#discussion_r1020081951
- Warn the user to update the predefined secret in cli next steps
💯
> fix: not able to log in if `NEXTAUTH_SECRET` is not set in dev

- www/src/pages/en/t3-collection.md
> docs(t3-collection): add tincy.pics in t3-collection

- cli/README.md
- www/src/components/docs/pageContent.astro
- www/src/components/landingPage/about.astro
- www/src/components/landingPage/banner.astro
- www/src/components/landingPage/cli.tsx
- www/src/components/landingPage/stack/stack.astro
- www/src/pages/en/deployment/vercel.md
- www/src/pages/en/installation.md
- www/src/pages/en/introduction.md
- www/src/pages/en/other-recs.md
- www/src/pages/en/t3-collection.md
- www/src/pages/en/usage/next-js.md
- www/src/pages/en/why.md
- www/src/styles/global.css
before:
after:
- updated Cal.com's description
- added a little text on the company part (would love to get more added here)
For 1-liners, the copy-button is now centered (maybe not perfectly but good enough) (and for larger codeblocks it aligns with the 1st row of text)
before:
after:
- more consistent spacing
- here's a demo of an iPad, iPhone 14 Max, iPhone 8 and Desktop side by side: https://share.cleanshot.com/HLr36x
- corrected colors of output text:
Use `npm create t3-app@latest`
> docs: small adjustments

- www/src/pages/en/usage/tailwind.md
> feat(docs): add mewtru's talk in tailwind docs

- www/src/components/landingPage/about.astro
- www/src/components/landingPage/banner.astro
- www/src/components/landingPage/stack/stack.astro
- www/src/components/landingPage/tweets/tweets.astro
- Copy for main blurb
- More copy updating, banner and more
---
---
💯
> docs: homepage copy pass by Theo

- www/src/pages/en/usage/next-auth.md
- www/src/styles/global.css
Closes #744 
---
- made list items text white
- fixed #744 
---
> feat: better styles for stuff

- www/src/pages/en/introduction.md
- www/src/pages/en/why.md
- Intro copy pass
- Flush out the why page a bit
---
---
💯
> docs: Copy pass on core docs

- www/src/components/navigation/themeToggleButton.astro
- www/src/layouts/docs.astro
- www/src/layouts/landingPage.astro
---
before:
https://user-images.githubusercontent.com/84864519/202182183-fba5d0a0-0434-4366-832e-975a57a366b8.mp4
after:
https://www.loom.com/share/a7d334e673ad4672a14ad15e254a2000
💯
> fix: flash of theme while refreshing

- .changeset/dull-parrots-rest.md
- cli/src/installers/envVars.ts
> fix: rename example env file

- pnpm-lock.yaml
- www/package.json
- www/src/components/headCommon.astro
> docs: test vercel analytics

- www/src/pages/en/usage/trpc.md
> docs: fix link to Trash's talk

- cli/src/installers/envVars.ts
- www/src/pages/en/folder-structure.md
- www/src/pages/en/usage/env-variables.md
---
we were using the old filename in some places
---
💯
> docs: correct .env.example filename

- www/src/pages/en/usage/tailwind.md
---
The PR fixes one small typo in tailwind.md.
💯
> docs: fix mispelling of 'separate'

- www/src/pages/en/introduction.md
"It's" is a contraction for "it is".
"Its" implies that something is belonging to a thing previously mentioned (OED).
---
"this stack is modular at it's core" was changed to "this stack is modular at its core"
---
💯
> docs: minor grammar fix

- www/src/pages/en/t3-collection.md
---
Update link to redirect to `next` branch instead of `main` to prevent confusion(https://github.com/t3-oss/create-t3-app/pull/803#issuecomment-1320469666)
💯
> docs(t3-collection): redirect to `next` branch instead of `main`

- www/src/pages/en/usage/trpc.md
Closes #811
---
Changes:
* Updated the trpc example to be more realistic.
* Fixed the missing comma in the example.
---
Before:
After:
Before:
After:
💯
> docs: fixed trpc examples

- www/src/config.ts
---
Updated the description to use the new banner text instead of the old one.
The current one uses the old text:
Beta:
Prod: 
💯
> docs: update meta description

- pnpm-lock.yaml
- www/astro.config.mjs
- www/package.json
- www/public/robots.txt
Closes #823 
---
Added sitemap plugin in docs
---
💯
> feat: add sitemap-index.xml for better SEO

- www/src/pages/en/usage/trpc.md
Little correction in wording to ease confusion. One of the advantages of tRPC is the autocompletion and typesafety.
---
Little correction in wording to ease confusion. One of the advantages of tRPC is the autocompletion and typesafety.
---
💯
> docs: correct tRPC advantages

- www/src/components/landingPage/tweets/tweets.astro
- www/src/components/navigation/githubIcon.astro
created a new token and added it to vercel
setting cache control to public to further reduce requests, maybe that helps?
> fix: twitter data

- www/TRANSLATIONS.md
- www/src/pages/en/deployment/docker.md
- www/src/pages/en/deployment/vercel.md
- www/src/pages/en/faq.md
- www/src/pages/en/folder-structure.md
- www/src/pages/en/installation.md
- www/src/pages/en/introduction.md
- www/src/pages/en/other-recs.md
- www/src/pages/en/t3-collection.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/en/usage/first-steps.md
- www/src/pages/en/usage/next-auth.md
- www/src/pages/en/usage/next-js.md
- www/src/pages/en/usage/prisma.md
- www/src/pages/en/usage/tailwind.md
- www/src/pages/en/usage/trpc.md
- www/src/pages/en/usage/typescript.md
- www/src/pages/en/why.md
Made the lang attribute explicit so that it's easier for translators to know what to update.
Also wrote a few guideline words for translations
> docs: lang attr and translating guide

- www/src/layouts/landingPage.astro
---
Fix bug caused by #840 disabling all links
---
💯
> fix: add pointer-events-none

- www/src/pages/en/t3-collection.md
Hi there! We've been using the T3 stack for our main app at [Layer3](https://beta.layer3.xyz) since August. 
We are super happy with it and would be happy to be featured as an example! 🚀
> docs: add Layer3 to list of companies using T3

- CONTRIBUTING.md
> docs: link to translation guide in contributing.md

- www/src/pages/en/installation.md
"explicitely"->"explicitly"
---
---
💯
> fix: typo in installation.md

- www/src/components/landingPage/tweets/tweets.astro
---
- add tom does tech tweet https://twitter.com/tomdoes_tech/status/1595652166173458434
- remove a tweet from the list for which the account seems to be dead https://twitter.com/anyuser/status/1571922865078915079
- add comments with links to tweets to make this section easier to maintain
---
💯
> docs: add tom does tech tweet and better document tweets

- pnpm-lock.yaml
- www/.prettierrc.cjs
- www/package.json
- www/src/components/docs/avatarList.astro
- www/src/components/docs/pageContent.astro
- www/src/components/docs/pagination.astro
- www/src/components/footer/footer.astro
- www/src/components/landingPage/about.astro
- www/src/components/landingPage/banner.astro
- www/src/components/landingPage/community/community.astro
- www/src/components/landingPage/community/communityCard.astro
- www/src/components/landingPage/stack/card.astro
- www/src/components/landingPage/stack/stack.astro
- www/src/components/landingPage/tweets/tweetCard.astro
- www/src/components/landingPage/tweets/tweetSlider.astro
- www/src/components/landingPage/tweets/tweets.astro
- www/src/components/navigation/githubIcon.astro
- www/src/components/navigation/leftSidebar.astro
- www/src/components/navigation/moreMenu.astro
- www/src/components/navigation/navbar.astro
- www/src/components/navigation/sidebarToggle.astro
- www/src/components/navigation/tableOfContents.astro
- www/src/components/navigation/themeToggleButton.astro
- www/src/layouts/docs.astro
- www/src/layouts/landingPage.astro
- www/src/pages/404.astro
- www/src/pages/themeTest.astro
see https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1312202554
> fix: tailwind prettier for astro

- www/src/config.ts
- www/src/pages/en/faq.md
- www/src/utils/pagination.ts
Minor improvement to avoid typos when adding new links and headers to the Sidebar.
Figured this might be useful for those working on translations.
Correct language code must be supplied in links.
Unknown outer headers will error. OuterHeaders type needs to be updated to add a new one. 
💯
> docs: improved Sidebar type

- .github/workflows/ci.yml
- cli/package.json
- pnpm-lock.yaml
This workflow fails on main.
Fixed the error and added manypkg to the lint step during CI
https://github.com/t3-oss/create-t3-app/actions/runs/3543450389/jobs/5949914813#step:6:65
> fix: invalid versions

- www/src/pages/en/usage/trpc.md
Closes #865
---
Changed "user" to "users" in the `page/users/[id].tsx` page in the TRPC docs page
💯
> fix: Typo in TRPC docs page

- www/src/pages/en/t3-collection.md
---
Changed "Speach" to "Speech" in the pages/en/t3-collection.md page in the T3 Collection docs page
---
💯
> fix: Typo in T3 Collection page

- www/src/components/docs/avatarList.astro
- www/src/pages/404.astro
> test: testing ci tokens

- www/src/styles/algolia/style.css
---
- A lot of visual improvements
- Fixed usage on mobile
- Fixed a bug where header and sidebars would disappear when opening the search bar
> docs: improve algolia docsearch styling

- .changeset/nasty-olives-notice.md
- cli/template/base/README.md
Closes #876 
---
- Update the scaffolded README.md
- Fix typos
---
💯
> feat: update scaffolded README.md

- www/src/styles/algolia/style.css
---
I'm not a big fan of the "3D" styling of many kbd buttons so I kept them more flat.
> docs: improve docsearch kbd styling

- CONTRIBUTING.md
- www/src/components/docs/breadCrumbs.tsx
- www/src/components/docs/pageContent.astro
- www/src/components/navigation/navbar.astro
- www/src/pages/en/other-recs.md
- www/src/styles/global.css
- www/vercel.json
---
- added breadcrumbs
- added missing redirects for site
- added a new contribution guideline
---
💯
> feat(www): add breadcrumbs & redirects

- .changeset/violet-pandas-sparkle.md
- cli/src/utils/validateAppName.ts
Refer: https://github.com/t3-oss/create-t3-app/issues/896#issuecomment-1330446356
💯
> fix(cli): fix wrong prompt when setting up project name

- www/src/pages/en/faq.md
> docs: add tom's new tutorial to learning resources

- www/src/components/docs/pageContent.astro
- www/src/components/landingPage/tweets/tweets.astro
- www/src/components/navigation/OnThisPageLinks.tsx
- www/src/layouts/docs.astro
- www/src/styles/global.css
---
Added on this page links for mobile/tablet devices for easily navigating between points.
---
Demo video
[demo-video.webm](https://user-images.githubusercontent.com/62164346/204088021-b0f6a270-bdf4-4e29-b8a7-789115cddb5f.webm)
💯
> feat: on this page links of article for mobile/tablet 

- www/src/components/docs/avatarList.astro
- www/src/components/docs/outdatedDocsBanner.astro
> fix(ci): i18n fetches broken

- www/src/components/docs/outdatedDocsBanner.astro
> docs: better outdated banner spacing on mobile

- .changeset/empty-lions-nail.md
- .changeset/lemon-walls-study.md
- cli/template/base/src/pages/index.tsx
- cli/template/page-studs/index/with-auth-trpc-tw.tsx
- cli/template/page-studs/index/with-auth-trpc.tsx
- cli/template/page-studs/index/with-trpc-tw.tsx
- cli/template/page-studs/index/with-trpc.tsx
- cli/template/page-studs/index/with-tw.tsx
- [ ✅ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ✅ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ✅ ] I performed a functional test on my final commit
---
Links on index page in template open in new tabs 🚀
💯
> feat: add blank target to base template

- www/src/pages/en/t3-collection.md
> docs: add new project to the collections list

- www/src/pages/en/deployment/vercel.md
---
Maybe we can get fewer questions about failing Vercel builds if we make it clear that most people don't need to mess with the config.
💯
> docs: Update vercel.md

- www/src/pages/en/t3-collection.md
---
Added `tauri-t3-app` to the t3-collection. Provides out-of-the-box "T3 Experience" for those using Next.js as their framework when building [Tauri](https://tauri.app) apps.
---
💯
> docs(t3-collection): add tauri-t3-app

- www/src/config.ts
---
missed some flags and stuff being in the wrong order while merging translation prs
💯
> chore: clean up config.ts

- www/src/components/navigation/OnThisPageLinks.tsx
Closes #940
changed the z-index of the menu from "2" to "11"
> fix: code title overlays "on this page" menu fix

- www/src/components/navigation/moreMenu.astro
Closes #944
---
- EN Dark
- EN Light
- Non-EN (RU)
💯
> feat(docs): add `Translate this page` button

- www/src/pages/en/folder-structure.md
`commited` -> `committed`
- -[x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- -[x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
---
---
💯
> fix(doc): a typo inside folder structure

- www/src/components/docs/outdatedDocsBanner.astro
> docs: improved spacing for outdated banner

- www/src/pages/en/why.md
> docs: remove extra whitespace

- www/src/components/docs/outdatedDocsBanner.astro
- www/src/components/docs/pagination.astro
---
1. Underline in outdated banner
- Before
- After
2. Underline in pagination
- Before
- After
💯
> docs: fix underline on hover

- www/src/styles/global.css
---
Added missing styles for h4. The difference is subtle but provides much-needed breathing room.
- Before
- After
💯
> docs: add styles for h4

- www/src/components/navigation/githubIcon.astro
---
repoistory -> repository
💯
> fix(www): fix typo

- www/src/components/docs/folderStructureForm.astro
- www/src/pages/en/folder-structure.mdx
---
1. NextAuth -> NextAuth.js
2. Add missing comma
---
💯
> docs(folder-structure): fix typo

- www/src/pages/ru/faq.md
- www/src/pages/ru/folder-structure.mdx
- www/src/pages/ru/t3-collection.md
- docs(ru): folder-structure update
- docs(ru): faq update
- docs(ru): t3-collection update
---
* updated folder_structure.mdx
* updated t3-collection links
* updated faq links
---
💯
> docs(ru): ru translation update

- www/src/pages/ar/folder-structure.mdx
---
- Changed the file to `.mjx`
- Fixed heading structure.
- Removed ملف and مجلد from the heading because some were misused and describing the wrong state of the folder/file.
---
💯
> docs(AR): new folder structure Arabic

- www/src/components/docs/folderStructureForm.astro
- www/src/components/navigation/tableOfContents.astro
Solves #984
---
Folder structure in side bar now properly disappear when their corresponding category is deselected in the main Folder Structure component. 
---
💯
> fix: folder structure list elements now properly disappear when deselected

- www/src/pages/en/t3-collection.md
- [✅] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [✅] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
> docs: add Azon to open source T3 projects

- www/src/pages/fr/usage/next-auth.md
- www/src/pages/no/usage/next-auth.md
---
- Add missing `async` for `fr` & `no` docs
💯
> docs(fr / no): add missing async

- www/src/pages/zh-hans/usage/next-auth.md
---
- Add missing async for `zh-hans` doc
💯
> docs(zh-hans): add missing async

- www/src/components/navigation/LanguageSelect.tsx
- www/src/styles/global.css
Closes #1002 
---
The language picker had default scrollbar now it has t3-scrollbar.
---
Before
After
💯
> docs: changed lang select scrollbar

- www/src/components/accessibility/jumpToContent.astro
Closes #1005 
---
- Made the jump to content accessibility button reflect the direction of the language using tailwind `ltr` and `rtl` modifiers
---
💯
> fix: horizontal scrolling in docs with RTL languages

- .changeset/giant-years-flash.md
- cli/src/utils/validateAppName.ts
> fix: allow dot name

- www/src/pages/en/t3-collection.md
---
Added analyzemyrepo.com to t3-collection
> docs: add analyzemyrepo.com to collection

- www/src/components/navigation/LanguageSelect.tsx
---
Refer: #1002 
- Before
- After
💯
> docs: make scrollbar show on right in RTL

- .changeset/big-scissors-compete.md
- cli/src/helpers/git.ts
- cli/src/index.ts
Closes #1026 
---
The CLI now stages the files on project initialization.
---
> feat: stage the template once created

- www/src/pages/en/t3-collection.md
same with [analyzemyrepo](https://github.com/CrowdDotDev/analyzemyrepo/pull/3)
---
---
💯
> fix(doc): a typo in t3-collection

- cli/template/base/src/env/client.mjs
- cli/template/base/src/env/schema.mjs
- cli/template/base/src/env/server.mjs
- cli/template/extras/src/env/schema/with-auth-prisma.mjs
- cli/template/extras/src/env/schema/with-auth.mjs
- cli/template/extras/src/env/schema/with-prisma.mjs
- www/src/pages/ar/usage/env-variables.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/fr/usage/env-variables.md
- www/src/pages/no/usage/env-variables.md
- www/src/pages/pt/usage/env-variables.md
- www/src/pages/ru/usage/env-variables.md
- www/src/pages/zh-hans/usage/env-variables.md
> feat: Deprecate Manual Declarations of `clientEnv` & `serverEnv`

- www/src/pages/en/usage/trpc.md
---
- fix typo regarding routers
> fix: fix typo regarding merging routers

- .changeset/fresh-melons-enjoy.md
- cli/template/base/src/env/client.mjs
- cli/template/base/src/env/schema.mjs
- cli/template/base/src/env/server.mjs
- cli/template/extras/src/env/schema/with-auth-prisma.mjs
- cli/template/extras/src/env/schema/with-auth.mjs
- cli/template/extras/src/env/schema/with-prisma.mjs
- www/src/pages/ar/usage/env-variables.md
- www/src/pages/en/usage/env-variables.md
- www/src/pages/fr/usage/env-variables.md
- www/src/pages/no/usage/env-variables.md
- www/src/pages/pt/usage/env-variables.md
- www/src/pages/ru/usage/env-variables.md
- www/src/pages/zh-hans/usage/env-variables.md
---
https://github.com/t3-oss/create-t3-app/issues/1069 has an issue that breaks client .env
I would like to keep all of the changes from that PR including a fixed version of the client stuff, but as a quick fix its easiest to just revert. We can add it back more carefully afterwards.
---
💯
> fix: undo env changes

- .changeset/smart-spoons-kiss.md
- cli/template/base/next.config.mjs
- cli/template/base/package.json
> chore: bump nextjs and add info bout appDir+i18n

- cli/template/extras/src/server/api/trpc/base.ts
- [ x ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ x ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x ] I performed a functional test on my final commit
---
Updated text literal.
---
💯
> fix: Add missing apostrophe to word "don't"

- cli/src/index.ts
Closes #1106 
---
- swapped the execution order of installing dependencies and git initialisation  so that the lockfile gets staged too
---
> fix: stage changes after installing deps

- www/src/pages/ar/deployment/docker.md
- www/src/pages/en/deployment/docker.md
- www/src/pages/fr/deployment/docker.md
- www/src/pages/no/deployment/docker.md
- www/src/pages/pl/deployment/docker.md
- www/src/pages/pt/deployment/docker.md
- www/src/pages/ru/deployment/docker.md
- www/src/pages/zh-hans/deployment/docker.md
> fix(doc): dockerFile builds fail as openssl1.1-compat doesn't exist

- www/src/pages/fr/usage/trpc.md
---
Updating the french documentation with change coming from #1110 
---
💯
> docs: update french translation with #1110

- www/src/components/docs/avatarList.astro
---
Should fix this error:
---
💯
> fix(www): check defined

- .changeset/config.json
---
Should trigger a CI check that a changeset is present when modifying files matching the glob
---
💯
> chore(ci): add `changedFilePatterns` to changeset config

- .github/workflows/ci.yml
should check wheter changeset is valid or not in regard to `changedFilePatterns`
So if there are changes to cli/src or cli/template this should fail if there isn't also a changeset for it
> chore(ci): add changeset step to ci

- www/src/components/landingPage/stack/card.astro
---
- fixed feature card header overflow
💯
> fix: feature card header overflow

- .github/workflows/translations.yml
> fix: translations action doesnt work on forks

- .github/workflows/translations.yml
---
@ JohnBakhmat changed their github user name, updating translations action accordingly 
💯
> fix: update JohnBakhmat name

- cli/template/extras/src/server/db.ts
- [x ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [] I performed a functional test on my final commit
---
I made a small change to make the use of environment variables in the db.ts consistent within the file itself. In the previous version it was using both the imported env variable and a direct access to process.env. This should not change any behaviour.
> chore: update db.ts to make the use of .env consistent

- .eslintrc.cjs
- .vscode/settings.json
- cli/src/cli/index.ts
- cli/src/helpers/git.ts
- cli/src/index.ts
- cli/src/utils/parseNameAndPath.ts
- cli/src/utils/renderVersionWarning.ts
- package.json
- pnpm-lock.yaml
- www/src/utils/fetchGithub.ts
---
I standardized JSDoc comments using a lint rule. When doing this:
- I took the liberty to rewrite some of the comments in more proper English.
- I removed some unnecessary hyphens. I don't think using hyphens is idiomatic in the ecosystem, e.g. the React codebase doesn't use them.
In the next PR after this is approved, I will extend the new rules to apply to the templates.
> chore: update linting config

- .github/workflows/translations.yml
- www/src/pages/no/folder-structure.md
- www/src/pages/no/installation.md
- www/src/pages/no/introduction.md
- www/src/pages/pl/faq.md
Reverts t3-oss/create-t3-app#1174
> Revert "test: Unique codeowner"

- .github/workflows/translations.yml
---
adds @MattFerreira18 to pt codeowners
---
💯
> chore: add MattFerreira18 to pt codeowners

- www/src/pages/pl/deployment/vercel.md
Closes 
---
Fixed numbered list in docs for Vercel deployments section in Polish language.
---
💯
> docs: fixed numbered list

- www/src/pages/en/usage/prisma.md
Closes #1204 
---
Added a link to the prisma migrate playground to the prisma section of the docs
---
> docs: added a link to the prisma migrate playground

- .github/workflows/translations.yml
- www/src/pages/pt/deployment/netlify.md
- www/src/pages/pt/usage/first-steps.md
- www/src/pages/pt/usage/prisma.md
---
- Added missing `lang` flag for Netfly page, this was causing to fallback to English when navigating away from that page.
- Slightly improved a few translations
💯
> docs: improve Portuguese translation

- cli/src/installers/dependencyVersionMap.ts
> fix: update a non-exist version of @tanstack/react-query

- .changeset/proud-papayas-hammer.md
- cli/src/installers/envVars.ts
> docs: Update comment in .env, as schema.mjs no longer exist

- www/src/components/navigation/leftSidebar.astro
operty added to left sidebar for Android Firefox nav scroll fix
Closes #1211
---
Added overflow auto to nav to fix the scroll issue on Firefox (https://github.com/t3-oss/create-t3-app/issues/1211)
---
💯
> fix: overflow pr

- www/src/pages/en/usage/prisma.md
---
- Keeping paths relative to root folder
---
💯
> docs: Fix path

- www/src/pages/zh-hans/faq.md
> docs: update chinese translation with #1227

- www/src/components/docs/openSourceAppList.tsx
---
Added Hitori to the list of open source apps
> docs: add hitori

- www/src/components/docs/openSourceAppList.tsx
Included a new project with 600+ stars that uses the T3 stack along with Solito, Tamagui and Clerk (there is also a version with Supabase). It includes also a Vscode plugin to improve the DX of adding screens and routes to your app. I am one of the many contributors, you can find the repo [here](https://github.com/chen-rn/CUA).
Hope this fits in this amazing list 😸 
Added a new open source app to the T3 collection.
> docs: Update openSourceAppList.tsx

- .changeset/tiny-news-move.md
- cli/template/base/package.json
> chore: bump nextjs

- .vscode/extensions.json
- .vscode/settings.json
---
- Updates `extensions.json` to recommend VSCode-MDX
- Updates `settings.json` to enable MDX language server support
---
Screenshots from my personal project
Before:
After:
💯
> feat: recommend mdx extension & intellisense 

- www/src/pages/en/other-recs.md
---
- added @shadcn/ui to other recommendations under styled component libraries
---
💯
> docs: add shadcn UI

- www/src/components/docs/openSourceAppList.tsx
---
Added Twitter clone to t3-collection, Sorry about [The first PR](https://github.com/t3-oss/create-t3-app/pull/1277) it closed automatically after I tried updating and syncing my fork with the repo.
> docs: add Twitter clone to t3-collection

- CONTRIBUTING.md
---
fixed a Spelling mistake of `Codesandbox` in `CONTRIBUTING.md`
💯
> docs: correct spelling mistake of Codesandbox

- www/src/pages/en/faq.md
Theo's latest Chirp tutorial covers the full process, from start to production. In my opinion, It's an amazing and complete learning resource that should be at the top of the list of recommended videos.
---
- Adds Theo's latest Chirp tutorial (https://www.youtube.com/watch?v=YkOSUVzOAA4) to the top of the list of recommended videos.
💯
> docs: Add Theo's Chirp tutorial to the list of recommended videos

- .github/workflows/translations.yml
---
lodisy renamed to escwxyz, see https://github.com/t3-oss/create-t3-app/issues/1121#issuecomment-1483748366
💯
> chore: update translations

- www/src/pages/ar/introduction.md
- www/src/pages/en/introduction.md
- www/src/pages/es/introduction.md
- www/src/pages/fr/introduction.md
- www/src/pages/no/introduction.md
- www/src/pages/pl/introduction.md
- www/src/pages/pt/introduction.md
- www/src/pages/ru/introduction.md
- www/src/pages/zh-hans/introduction.md
Closes #1292 
---
Replaces old overview with tutorial
---
💯
> feat(docs): replace old overview with tutorial

- package.json
- pnpm-lock.yaml
---
Ive updated the pnpm version inside the package.json to 8.1.0
---
lol
💯
> build: update pnpm version to 8.1.0 

- www/src/pages/en/faq.md
---
Add a section to the FAQ about how to keep a T3 app up to date
---
💯
> docs: add "its your app" faq section

- www/src/components/docs/breadCrumbs.tsx
---
- removed type casts from `sidebar` array using spread which makes TS happy
- removed `Entry` type and used inference instead
- added `OuterHeaders` return type to make sure function returns correct value
💯
> feat(docs): remove unnecessary type casts

- www/src/components/docs/breadCrumbs.tsx
- www/src/components/docs/callout.tsx
- www/src/components/docs/pageContent.astro
- www/src/components/docs/pagination.astro
- www/src/pages/en/deployment/netlify.mdx
- www/src/pages/en/faq.mdx
- www/src/pages/en/installation.mdx
- www/src/pages/en/t3-collection.mdx
- www/src/pages/en/usage/env-variables.mdx
Closes #1340 
---
- fixes an issue where breadcrumbs would be cut off if they were too long
- fixes an issue where the arrows between breadcrumbs would be shrunk on smaller screens
- fixes mentioned issue (ending `/` would cause breadcrumbs to show `undefined` instead of the page name)
- aligns correctly the text and the icon in a `<Pagination />` component
- adds a `<Callout />` component with 3 modes: `ℹ️ info`, `⚠️ warning` and `💡 tip`
- uses a `<Callout />` component in other files (`netlify.mdx`, `faq.mdx`, `installation.mdx`, `t3-collection.mdx` and `env-variables.mdx`)
```tsx
<Callout type={"info" | "warning" | "tip"}>
Content of the component.
</Callout>
```
---
| ℹ️ info …
> feat(docs): breadcrumbs and pagination fixes, callout component

- www/src/components/docs/companyList.tsx
As recommended by Nexxel on Discord
---
Added [Civitai](https://civitai.com) to the list of companies using the t3 stack.
---
😬 
💯
> docs: add Civitai to company list

- .changeset/blue-walls-admire.md
- cli/template/base/next.config.mjs
- cli/template/base/src/env.mjs
- cli/template/extras/src/env/with-auth-prisma.mjs
- cli/template/extras/src/env/with-auth.mjs
- cli/template/extras/src/env/with-prisma.mjs
Closes #1357
---
Improves boolean coercion of the `SKIP_ENV_VALIDATION` variable.
---
💯
> feat: improve boolean coercion of `SKIP_ENV_VALIDATION`

- www/src/pages/ar/installation.mdx
- www/src/pages/es/installation.mdx
- www/src/pages/fr/installation.mdx
- www/src/pages/no/installation.mdx
- www/src/pages/pl/installation.mdx
- www/src/pages/pt/installation.mdx
- www/src/pages/ru/installation.mdx
- www/src/pages/zh-hans/installation.mdx
---
Wrapped warning message in installation page in the docs in every translation according to English translation
---
Before
After
💯
> docs: add Callout component to installation page in every translation

- cli/README.md
---
Change logo in README to new T3 logo.
---
💯
> feat: Change logo in README

- www/src/components/navigation/Search.tsx
- www/src/components/navigation/githubIcon.astro
> docs: fix color transitions

- www/src/components/docs/openSourceAppList.tsx
This PR adds [my own project, T3 Blog](https://github.com/leojuriolli7/t3-blog) to the  list of open source apps built with the t3 stack. It is a forum built with the T3 Stack. 
---
Added my own open source project, T3 Blog (https://github.com/leojuriolli7/t3-blog) to the list of open source apps using t3 stack.
💯
> docs: add t3 blog to the open source projects list

- .changeset/short-poets-swim.md
accidentally merged a changeset that shouldn't have been there in the japanese translation pr
> fix: remove changeset

- www/src/components/docs/openSourceAppList.tsx
---
Added Checkinout to t3-collection
> docs: add Checkinout to t3-collection

- www/src/pages/fr/why.md
Changed "Si vous êtes curieux de connaître" to "Si vous voulez en savoir plus sur" since the original wording didn't sound French
---
Changed "Si vous êtes curieux de connaître" to "Si vous voulez en savoir plus sur" since it didn't sound French
---
💯
> docs: worded some French better

- upgrade/README.md
- upgrade/src/lib/utils.ts
* Use octokit instead of fetch
* filter out versions under 5.10.3
* fix mobile dropdowns
* add readme
> fix: Minor fixes

- cli/src/cli/index.ts
> chore: fixed e2e tests

- upgrade/src/lib/utils.ts
> fix: Add missing versions that were excluded because they contain 0's in them

- upgrade/src/app/diff/[slug]/download-button.tsx
- upgrade/src/app/diff/[slug]/page.tsx
- upgrade/src/app/not-found.tsx
- upgrade/src/app/upgrade-panel.tsx
> fix: update diff link to include dash between versions and features

- www/src/pages/zh-hans/faq.mdx
---
Update faq Chinese document
---
💯
> docs: update chinese translation

- www/src/pages/en/faq.mdx
Closes #1467 
---
Added warning on english faq page that some tutorials might be outdated and removed nexxel's tutorial.
---
💯
> docs: rm nexxel's tutorial

- www/src/pages/en/usage/env-variables.mdx
---
fixed two sentences that were a bit unclear, and added notes on type coercion
💯
> docs: fix unclear env bits and add coercion docs

- cli/template/base/next.config.mjs
Add new line between config definition and config export.
---
Add new line between config definition and config export.
> fix: Add new line between config definition and config export.

- www/src/components/docs/companyList.tsx
---
- Add GreatFrontEnd as an example that's using T3 stack.
---
💯
> docs: add GreatFrontEnd to company list

- www/src/pages/en/other-recs.md
---
Added Umami Cloud in Other Recommendations Page
---
> docs: add Umami Cloud in Other Recommendations Page

- cli/src/installers/dependencyVersionMap.ts
Bump superjson to 1.13.1
Bump other minor versions
> bump superjson to 1.13.1

- www/src/components/docs/openSourceAppList.tsx
---
sozluk-clone added to t3-collection
> docs: add sozluk-clone to t3-collection

- .gitignore
- cli/template/base/next.config.mjs
---
- adjusted comment about `appDir` in `next.config.mjs` as it is no longer experimental
- also added `*.tsbuildinfo` to repo `.gitignore` as `pnpm check` generated one 
---
💯
> Fix appdir comment

- www/src/components/docs/companyList.tsx
Hi! I'm Co-founder and CTO of River. We'd like to share some ❤️ since we're having a great experience using T3 stack for our web app :) 
---
Add `River` as an example of company that's using T3 stack.
---
💯
> docs: add River to the list of companies using t3 stack

- cli/package.json
- cli/template/base/package.json
- pnpm-lock.yaml
- upgrade/package.json
> chore: version bump some stuff in base template

- pnpm-lock.yaml
- www/package.json
Closes #1533 1533
---
bumped astro to resolve #1533.
---
💯
> build: bump astro

- www/src/components/docs/folderStructureDiagram.astro
- www/src/components/navigation/tableOfContents.astro
- www/src/pages/ar/folder-structure.mdx
- www/src/pages/en/folder-structure.mdx
- www/src/pages/es/folder-structure.mdx
- www/src/pages/fr/folder-structure.mdx
- www/src/pages/ja/folder-structure.mdx
- www/src/pages/no/folder-structure.mdx
- www/src/pages/pl/folder-structure.mdx
- www/src/pages/pt/folder-structure.mdx
- www/src/pages/ru/folder-structure.mdx
- www/src/pages/zh-hans/folder-structure.mdx
---
#1501 made some changes without the relevant docs updates, so here they are :).
---
💯
> docs: update the doc based of cli changes

- www/src/components/docs/companyList.tsx
---
Add [FlowGPT](https://flowgpt.com/) to Company List
---
💯
> docs: Add FlowGPT to Company List

- www/src/components/docs/openSourceAppList.tsx
---
Add [OpenBio.app](https://openbio.app) to Open source app list
💯
> docs: add openbio.app to OSS app list

- cli/prettier.config.mjs
- upgrade/prettier.config.mjs
- www/prettier.config.mjs
Closes #1555
---
Replace `^[../]` with `^[.][.]/` and `^[./]` with `^[.]/`
💯
> fix(prettier-config): fix import order

- www/src/pages/ru/other-recs.md
- www/src/pages/ru/t3-collection.mdx
> docs(ru): Updating ru translation

- www/src/pages/en/usage/next-auth.mdx
> docs: update session callback

- www/src/config.ts
- www/src/pages/fr/examples.mdx
> Add examples translation for french language

- www/src/components/docs/openSourceAppList.tsx
Adding new example for the project that I build with t3 stack. I've create a simple notes with help of t3stack
- [✅ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ✅] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ✅] I performed a functional test on my final commit
---
I've added one array for my project https://code-notes-app.vercel.app/
---
💯
> docs(add new project): Add new example project for notes taking app

- .changeset/light-steaks-happen.md
- cli/src/helpers/logNextSteps.ts
- cli/src/index.ts
> feat: show callout when scaffolding with app router

- www/src/components/docs/openSourceAppList.tsx
> docs: Update openSourceAppList.tsx add rao.pics

- .changeset/fluffy-spiders-lie.md
- pnpm-lock.yaml
- www/package.json
resolves https://github.com/t3-oss/create-t3-app/security/dependabot/13
> fix: update sharp

- www/src/components/docs/openSourceAppList.tsx
> docs: Add eboto to openSourceAppList.tsx

- cli/template/extras/src/server/db/drizzle-schema-auth.ts
@ryanagillie 
- [ x ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ x ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x ] I performed a functional test on my final commit
---
Add sessions to userRelations in drizzle-schema-auth
💯
> fix: Add sessions relation in drizzle-schema-auth

- www/src/pages/en/deployment/netlify.mdx
- www/src/pages/en/deployment/vercel.md
- www/src/pages/en/installation.mdx
- www/src/pages/en/usage/prisma.md
- www/src/pages/en/usage/trpc.md
- www/src/pages/en/why.md
Please review and feel free to suggest changes.
---
---
💯
> docs: Fixed some typo in the documentation

- www/src/components/docs/openSourceAppList.tsx
Closes https://github.com/t3-oss/create-t3-app/issues/1675
the app / repo no longer exist
💯
> docs: remove hitori from app list

- www/src/components/docs/companyList.tsx
- www/src/components/docs/openSourceAppList.tsx
---
- feat: replace other josh's showcase entry
- feat: add papertrail as a t3 company
> feat: replace josh's showcase entry

- www/src/components/docs/breadCrumbs.tsx
---
Removed redundant expression
---
N/A
> fix: remove redundant expression

- .changeset/thick-eggs-breathe.md
- cli/package.json
- cli/src/installers/dependencyVersionMap.ts
- pnpm-lock.yaml
> bump-drizzle

- www/src/pages/en/usage/prisma.md
Module '"../src/server/db"' has no exported member 'prisma'
> fix: ref db not prisma

- www/src/pages/ar/usage/trpc.md
- www/src/pages/en/usage/trpc.md
- www/src/pages/es/usage/trpc.md
- www/src/pages/fr/usage/trpc.md
- www/src/pages/ja/usage/trpc.md
- www/src/pages/no/usage/trpc.md
- www/src/pages/pl/usage/trpc.md
- www/src/pages/pt/usage/trpc.md
- www/src/pages/ru/usage/trpc.md
- www/src/pages/zh-hans/usage/trpc.md
Closes #1709 
---
Made changes in the trpc docs according to #1709 
---
💯
> docs: update trpc docs to use `t.createCallerFactory()` 

- www/src/pages/en/usage/trpc.md
They renamed useContext to useUtils
https://trpc.io/docs/client/react/useUtils
---
---
💯
> docs: change useContext to useUtils

- cli/template/extras/start-database/mysql.sh
- cli/template/extras/start-database/postgres.sh
---
Fixed "Lunux" typo
---
n/a
💯
> docs: Fix typo

- www/src/pages/en/usage/trpc.md
> docs: fix broken link

- cli/README.md
- cli/template/base/README.md
Closes #1753 
---
This PR will add the Drizzle link to the template base README.md and the CLI README.md among other technology links.
---
Drizzle added to the template base README.md
Drizzle added to the cli README.mds
> docs: add drizzle to README in template

- www/src/pages/en/deployment/docker.md
Closes #1758
---
Updated a package in the Dockerfile and made Docker compose docs more readable.
---
> docs: Update Docker documentation

- www/src/config.ts
- www/src/pages/pl/examples.mdx
---
I added the "examples" page to the documentation with translation in Polish.
---
💯
> docs: adding a translation in Polish for the "examples" page

- .changeset/twelve-cars-guess.md
- cli/template/extras/src/server/db/db-prisma-planetscale.ts
- cli/template/extras/src/server/db/db-prisma.ts
> feat: support prisma extends

- www/src/components/docs/openSourceAppList.tsx
> docs: add improvdb to openSourceAppList.tsx

- www/src/components/docs/openSourceAppList.tsx
---
Added a new repo in t3 collection page
---
> docs: added todo-mvc to open source collection

- .changeset/long-cobras-dress.md
- cli/package.json
- cli/template/base/package.json
- pnpm-lock.yaml
- upgrade/package.json
---
Updated Next.js from 14.1.3 to 14.2.1
> chore: update next to 14.2.1

- .changeset/unlucky-poems-appear.md
- cli/src/cli/index.ts
removes experimental label and flips the default
> chore: stabilize app router and make it defautl

- .changeset/unlucky-poems-appear.md
- cli/src/cli/index.ts
Reverts t3-oss/create-t3-app#1831
didn't mean to merge this without approval
> Revert "chore: stabilize app router and make it defautl"

- .changeset/five-llamas-drop.md
- cli/package.json
- cli/template/base/package.json
- pnpm-lock.yaml
- upgrade/package.json
- www/package.json
Proper fix for https://github.com/t3-oss/create-t3-app/issues/1836
> chore: bumps zod and t3-env

- cli/package.json
- cli/template/base/package.json
- pnpm-lock.yaml
- upgrade/package.json
- www/package.json
x-ref https://github.com/t3-oss/t3-env/pull/224
> bump zod and t3-env

- www/src/components/docs/openSourceAppList.tsx
> added sunal-rahal(an app bootstraped using t3) to docs

- www/src/components/docs/openSourceAppList.tsx
---
Updated the domain from railtrack.flk.li to railtrack.ch
> docs: update Railtrack domain in T3 collection

- www/src/components/docs/openSourceAppList.tsx
This PR adds my new [T3 turborepo template with biomejs](https://github.com/rajatsandeepsen/t3-turbo-biome) as primary linting and formatting tool fully configured with both shadcn web and native ui to t3 collection in docs
Fixed previous issue in PR #1762
---
T3 turborepo template  with
1. [biomejs](https://biomejs.dev/guides/big-projects/) as primary linting and formating tool 
2. shadcn [web ui](https://github.com/shadcn-ui/ui)
3. shadcn [native ui](https://github.com/mrzachnugent/react-native-reusables) by @mrzachnugent
💯
> docs: add T3-Turbo-biome to collection with both shadcn native & web ui

- .changeset/five-kangaroos-sin.md
- cli/template/base/_gitignore
Closes #1904 
---
Add ```.idea``` to ```.gitignore``` as mentioned in this [issue](https://github.com/t3-oss/create-t3-app/issues/1904).
---
💯
> chore: ignore .idea

- www/src/pages/en/faq.mdx
---
I updated the FAQ to link to Theo's updated t3 app tutorial that uses the App Router, and changed the section about `app` vs. `pages` to reflect the current situation.
> docs: update FAQ to reflect app router support

- www/src/pages/en/other-recs.md
PostHog is really really good lol, and since Theo used it in his latest CT3 video might as well recommend it here.
> docs: Add PostHog to analytics recommendations

- www/src/pages/en/installation.mdx
---
in `installation.mdx` there was a type `Inlcude` instead of `include`
---
💯
> chore:docs(en): Fix typo in installation.mdx

- www/src/components/docs/openSourceAppList.tsx
---
Added my project, Squeak, to the openSourceAppList page.
---
💯
> docs: add Squeak to openSourceAppList.tsx

- .changeset/red-bags-beam.md
- cli/template/extras/src/server/db/schema-drizzle/base-postgres.ts
- cli/template/extras/src/server/db/schema-drizzle/with-auth-postgres.ts
Closes #1980 
---
- Change drizzle with PostgresQL to use identity columns
---
> fix: use PostgreSQL identity columns with drizzle

- .changeset/thin-hats-reflect.md
- cli/template/extras/start-database/mysql.sh
- cli/template/extras/start-database/postgres.sh
---
In `start-database.sh` some variables are built from `DATABASE_URL` and some aren't. This PR changes that so all variables are built from it.
- `DB_NAME` added
- `DB_CONTAINER_NAME` uses `"$DB_NAME-postgres"`
---
💯
> chore: upgrades to start-database.sh

- www/src/components/docs/openSourceAppList.tsx
> docs: add Ray to openSourceAppList

- .changeset/gold-beans-kiss.md
- cli/src/helpers/scaffoldProject.ts
changeset
---
Fix cli cancelation not working when `ctrl+c` press 
---
💯
> fix: cli cancel not working

- www/src/pages/en/usage/drizzle.mdx
---
- Update drizzle docs to remove incorrect reference to Prisma
---
💯
> docs: Update drizzle.mdx to replace Prisma reference with Drizzle

- .changeset/young-clubs-lay.md
- cli/template/extras/src/trpc/react.tsx
Closes #2086 
---
- Change IF statement to nullish coalescing operator to fix eslint error preventing build
---
💯
> fix: add nullish coalescing operator to fix eslint error

- www/src/components/docs/openSourceAppList.tsx
> docs: update link details for Prisma Editor in openSourceAppList
